SET LINES 300 PAGESIZE 1000
SELECT 'ALTER ' || LOWER(DECODE(OBJECT_TYPE,'PACKAGE BODY', 'PACKAGE',OBJECT_TYPE)) || ' ' || OWNER || '.' || OBJECT_NAME || ' ' || DECODE (OBJECT_TYPE,'PACKAGE BODY','COMPILE BODY','COMPILE') || ';'
FROM DBA_OBJECTS 
WHERE STATUS <> 'VALID' 
--AND OWNER='UDMF_UI'
AND OBJECT_NAME='PRC_VARIANCE_DTLS_ON_RECON_DATA'
ORDER BY OBJECT_NAME;
/


SELECT OWNER, NAME, TYPE, LINE, POSITION, TEXT
FROM DBA_ERRORS
WHERE OWNER = '<owner>'
AND NAME = '<package_name>'
AND TYPE = 'PACKAGE BODY'
ORDER BY LINE, POSITION;


SELECT COUNT(*) FROM DBA_OBJECTS WHERE OWNER='TASY' AND STATUS <> 'VALID' and OBJECT_NAME not in ('org/jdom/xpath/JaxenXPath','/e987b714_JaxenXPathNSContext');

SPOOL RECOMPILA.SQL
SELECT 'ALTER ' || OBJECT_TYPE || ' ' || OWNER || '.' || OBJECT_NAME || ' COMPILE;' FROM ALL_OBJECTS WHERE STATUS = 'INVALID' AND OWNER = 'DBAMV' AND OBJECT_TYPE NOT IN ('PACKAGE BODY', 'MATERIALIZED VIEW') ;
SPOOL OFF;



select OBJECT_TYPE, STATUS, count(1) QTD 
from dba_objects 
where owner = 'DBAASS' AND STATUS = 'INVALID' 
GROUP BY(OBJECT_TYPE, STATUS);



spool /orastb01/upgrade_info.log
@utlu112i.sql
spool off;


Sql > startup upgrade

spool /orastb01/upgrade.log
@catupgrd.sql
spool off;



EXEC UTL_RECOMP.RECOMP_SERIAL ('DBATJ');



SET LINES 300 PAGESIZE 1000
SELECT 
	'ALTER ' || LOWER(DECODE(OBJECT_TYPE,'PACKAGE BODY',
	'PACKAGE',OBJECT_TYPE)) || ' ' || OBJECT_NAME || ' ' || DECODE (OBJECT_TYPE,'PACKAGE BODY','COMPILE BODY','COMPILE') || ';'
FROM 
	ALL_OBJECTS 
WHERE 
	STATUS <> 'VALID' 
	--AND OWNER='DBATJ'
	AND OBJECT_NAME IN ('DUE_DATE_MIGRATION','POST_CALL_MIGRATION');