COL GNAME FORMAT A10
COL DBNAME FORMAT A10
COL FILE_TYPE FORMAT A30
COL MB FORMAT 999999999
COL GB FORMAT 999999999
COL "#FILES" FORMAT 999999999
SELECT
GNAME, DBNAME, FILE_TYPE, ROUND(SUM(SPACE)/1024/1024) MB, ROUND(SUM(SPACE)/1024/1024/1024) GB, COUNT(*) "#FILES"
FROM
		( SELECT
		GNAME, REGEXP_SUBSTR(FULL_ALIAS_PATH, '[[:ALNUM:]_]*',1,4) DBNAME, FILE_TYPE, SPACE
		FROM
				( SELECT
				CONCAT('+'||GNAME, SYS_CONNECT_BY_PATH(ANAME, '/')) FULL_ALIAS_PATH, SYSTEM_CREATED, FILE_TYPE, SPACE, GNAME
				FROM
						( SELECT
						B.NAME GNAME, A.PARENT_INDEX  PINDEX, A.NAME ANAME, A.REFERENCE_INDEX RINDEX , A.SYSTEM_CREATED, C.TYPE FILE_TYPE, C.SPACE
						FROM
						V$ASM_ALIAS A, V$ASM_DISKGROUP B, V$ASM_FILE C
						WHERE
						A.GROUP_NUMBER = B.GROUP_NUMBER AND A.GROUP_NUMBER = C.GROUP_NUMBER(+) AND A.FILE_NUMBER = C.FILE_NUMBER(+) AND A.FILE_INCARNATION = C.INCARNATION(+) ) 
				START WITH 
				(MOD(PINDEX, POWER(2, 24))) = 0 AND RINDEX IN
				( SELECT 
				A.REFERENCE_INDEX
				FROM   
				V$ASM_ALIAS A, V$ASM_DISKGROUP B
				WHERE  
				A.GROUP_NUMBER = B.GROUP_NUMBER AND    MOD(A.PARENT_INDEX, POWER(2, 24)) = 0) 
				CONNECT BY 
				PRIOR RINDEX = PINDEX )
		WHERE NOT FILE_TYPE IS NULL AND   SYSTEM_CREATED = 'Y' )
GROUP BY
GNAME, DBNAME, FILE_TYPE
ORDER BY
GNAME, DBNAME, FILE_TYPE
/