--AUTO ADD DATAFILE
CREATE OR REPLACE VIEW SYS.ADD_DATAFILE_VIEW AS
	SELECT 
		REC.TBS_CNT, 
		ROUND(SUM(DF.BYTES)/1024/1024/1024,2) FREE_SPACE, 
		REC.TABLESPACE_NAME, 
		REC.TOT_SIZE, 
		REC.MAX_SIZE, 
		REC.FREE_GB, 
		REC.USAGE_PCT, 
		'ALTER TABLESPACE '||REC.TABLESPACE_NAME|| ' ADD DATAFILE '''|| SUBSTR(D.FILE_NAME,1,LENGTH (D.FILE_NAME)-4) ||'_'|| TO_CHAR (REC.TBS_CNT +1) ||'.ORA'' SIZE 1G AUTOEXTEND ON NEXT 256M MAXSIZE 16G' ADD_DATAFILE
	FROM 
		DBA_DATA_FILES D,
		(
		SELECT 
			COUNT(*) TBS_CNT, 
			MIN(DD.FILE_ID) MIN_FILE_ID, 
			DD.TABLESPACE_NAME, 
			ROUND(SUM(DD.BYTES/1024/1024/1024)) TOT_SIZE, 
			ROUND (SUM(NVL(NULLIF(DD.MAXBYTES,0),DD.BYTES)/1024/1024/1024)) MAX_SIZE, 
			ROUND(SUM(NVL(NULLIF(DD.MAXBYTES,0),DD.BYTES)/1024/1024/1024)-ROUND(SUM(DD.BYTES)/1024/1024/1024)) FREE_GB, 
			100*ROUND(SUM(DD.BYTES/1024/1024/1024)/SUM(NVL(NULLIF(DD.MAXBYTES,0),DD.BYTES)/1024/1024/1024),3) USAGE_PCT
		FROM  
			DBA_DATA_FILES DD, 
			DBA_TABLESPACES DT
		WHERE
			DD.TABLESPACE_NAME=DT.TABLESPACE_NAME 
			AND DD.STATUS='AVAILABLE' 
			AND DT.STATUS<>'READ ONLY' 
			AND DT.CONTENTS='PERMANENT'
		GROUP BY 
			DD.TABLESPACE_NAME
		) REC,
		DBA_FREE_SPACE DF
	WHERE 
		D.FILE_ID=REC.MIN_FILE_ID 
		AND DF.TABLESPACE_NAME=REC.TABLESPACE_NAME
	GROUP BY 
		REC.TBS_CNT, 
		REC.TABLESPACE_NAME, 
		REC.TOT_SIZE, 
		REC.MAX_SIZE, 
		REC.FREE_GB, 
		REC.USAGE_PCT, 
		'ALTER TABLESPACE '||REC.TABLESPACE_NAME|| ' ADD DATAFILE '''|| SUBSTR(D.FILE_NAME,1,LENGTH (D.FILE_NAME)-4) ||'_'|| TO_CHAR (REC.TBS_CNT+1) ||'.ORA'' SIZE 1G AUTOEXTEND ON NEXT 256M MAXSIZE 16G'
	ORDER BY 
		REC.USAGE_PCT DESC;
 

--and for asm or where db_create_file_dest is setup it is a little bit shorter 
CREATE OR REPLACE VIEW SYS.ADD_DATAFILE_VIEW AS
	SELECT 
		REC.TBS_CNT, 
		ROUND(SUM(DF.BYTES)/1024/1024/1024,2) FREE_SPACE, 
		REC.TABLESPACE_NAME, 
		REC.TOT_SIZE, 
		REC.MAX_SIZE, 
		REC.FREE_GB, 
		REC.USAGE_PCT, 
		'ALTER TABLESPACE '||REC.TABLESPACE_NAME|| ' ADD DATAFILE ' ADD_DATAFILE
	FROM 
		DBA_FREE_SPACE DF,
		(
		SELECT 
			COUNT(*) TBS_CNT, 
			MIN(DD.FILE_ID) MIN_FILE_ID, 
			DD.TABLESPACE_NAME, 
			ROUND(SUM(DD.BYTES/1024/1024/1024)) TOT_SIZE, 
			ROUND(SUM(NVL(NULLIF(DD.MAXBYTES,0),DD.BYTES)/1024/1024/1024)) MAX_SIZE, 
			ROUND(SUM(NVL(NULLIF(DD.MAXBYTES,0),DD.BYTES)/1024/1024/1024)-ROUND(SUM(DD.BYTES)/1024/1024/1024)) FREE_GB, 
			10*ROUND(SUM(DD.BYTES/1024/1024/1024)/SUM(NVL(NULLIF(DD.MAXBYTES,0),DD.BYTES)/1024/1024/1024),3) USAGE_PCT
		FROM  
			DBA_DATA_FILES DD, 
			DBA_TABLESPACES DT
		WHERE   
			DD.TABLESPACE_NAME=DT.TABLESPACE_NAME 
			AND DD.STATUS='AVAILABLE' 
			AND DT.STATUS<>'READ ONLY' 
			AND DT.CONTENTS='PERMANENT'
		GROUP BY 
			DD.TABLESPACE_NAME
		--HAVING 
			--100*ROUND(SUM(DD.BYTES/1024/1024/1024)/SUM(NVL(NULLIF(DD.MAXBYTES,0),DD.BYTES)/1024/1024/1024),3)>75
			--AND ROUND(SUM(NVL(NULLIF(DD.MAXBYTES,0),DD.BYTES)/1024/1024/1024))-ROUND(SUM(DD.BYTES/1024/1024/1024))<100
		) REC
	WHERE 
		DF.TABLESPACE_NAME=REC.TABLESPACE_NAME
	GROUP BY 
		REC.TBS_CNT, 
		REC.TABLESPACE_NAME, 
		REC.TOT_SIZE, 
		REC.MAX_SIZE, 
		REC.FREE_GB, 
		REC.USAGE_PCT, 
		'ALTER TABLESPACE '||REC.TABLESPACE_NAME|| ' ADD DATAFILE '''
	ORDER BY 
		REC.USAGE_PCT DESC;


--EXECUTE 
BEGIN
	FOR I IN (SELECT ADD_DATAFILE FROM SYS.ADD_DATAFILE_VIEW WHERE FREE_SPACE < 30 AND USAGE_PCT > 85)
	LOOP
		EXECUTE IMMEDIATE I.ADD_DATAFILE;
	END LOOP;
END;
/﻿