SET LINES 300
SET PAGESIZE 1000
SET LONG 1000
COL "START#" FOR A25
COL "B_SID" FOR 99999
COL "B_SER#" FOR 99999
COL "EVENT" FOR A30
COL "CPU" FOR 999999
COL "WAIT" FOR 999999
COL "IO" FOR 999999
COL "TOTAL" FOR 999999
COL "DURATION#" FOR A23
COL "TEXT" FOR A40
SELECT  
	MIN(SAMPLE_TIME) "START#", MAX(SAMPLE_TIME)-MIN(SAMPLE_TIME) "DURATION#", ASH.SQL_ID, ASH.TOP_LEVEL_SQL_ID, ASH.BLOCKING_SESSION "B_SID", ASH.BLOCKING_SESSION_SERIAL# "B_SER#", ASH.EVENT "EVENT", SUM(DECODE(ASH.SESSION_STATE,'ON CPU',1,0)) "CPU", SUM(DECODE(ASH.SESSION_STATE,'WAITING',1,0)) - SUM(DECODE(ASH.SESSION_STATE,'WAITING',DECODE(ASH.WAIT_CLASS,'USER I/O',1,0),0)) "WAIT", SUM(DECODE(ASH.SESSION_STATE,'WAITING',DECODE(ASH.WAIT_CLASS,'USER I/O',1,0),0)) "IO", SUM(DECODE(ASH.SESSION_STATE,'ON CPU',1,1)) "TOTAL", SUBSTR (S.SQL_TEXT,1,100) "TEXT"
FROM 
	DBA_HIST_ACTIVE_SESS_HISTORY ASH
LEFT JOIN V$SQL S ON S.SQL_ID=ASH.SQL_ID
LEFT JOIN V$SESSION SES ON S.SQL_ID=SES.SQL_ID
WHERE 
	ASH.SQL_ID IS NOT NULL AND ASH.SAMPLE_TIME BETWEEN TO_DATE('19.10.2020 09.50','DD.MM.YYYY HH24.MI') AND TO_DATE('19.10.2020 23.00','DD.MM.YYYY HH24.MI')
	GROUP BY ASH.SESSION_ID,ASH.SESSION_SERIAL#,ASH.EVENT,ASH.SQL_ID,ASH.TOP_LEVEL_SQL_ID,ASH.BLOCKING_SESSION, ASH.BLOCKING_SESSION_SERIAL#,SUBSTR(S.SQL_TEXT,1,100)
HAVING  
	SUM(DECODE(ASH.SESSION_STATE,'WAITING',1,0))-SUM(DECODE(ASH.SESSION_STATE,'WAITING',DECODE(ASH.WAIT_CLASS,'USER I/O',1,0),0))>0 AND MAX(SAMPLE_TIME)-MIN(SAMPLE_TIME)> INTERVAL '30' SECOND
ORDER BY 1 ASC ;