ALTER SESSION SET NLS_DATE_FORMAT='DD-MON-YYYY HH24:MI:SS';
--SET LINES 280 PAGESIZE 1000 LONG 15000 ECHO ON TIME ON TIMING ON TRIM ON TRIMSPOOL ON UNDERLINE =
SET LINES 280 PAGESIZE 1000 LONG 15000 ECHO ON TRIM ON TRIMSPOOL ON UNDERLINE =
COL HOST_NAME FOR A20
COL OWNER FOR A20
COL TABLE_OWNER FOR A20
COL TABLE_NAME FOR A30
COL PARTITION_NAME FOR A20
COL SUBPARTITION_NAME FOR A20
SET TERMOUT OFF
COLUMN today_col NEW_VALUE today
SELECT TO_CHAR (SYSDATE, 'YYYYMMDD') AS today_col FROM dual;
SET TERMOUT ON
SPOOL 'cde_gather_table_stats_&today..log'
=========================================================================================================================================
SELECT INSTANCE_NAME, HOST_NAME, SYSDATE FROM V$INSTANCE;
=========================================================================================================================================
SELECT * FROM DBA_TAB_MODIFICATIONS WHERE TABLE_NAME IN (
'STG_BAN_EVENTS',
'TU_CREDIT_SCORE',
'DATA_QUALITY_METRICS',
'BUSINESS_METRICS',
'IOT_PRODUCTS',
'IOT_ONGOING_AMOUNT',
'VW_IOT_PRODUCTS',
'IOT_PRODUCTS_LINES',
'IOT_AGREEMENT_UPDATED',
'COLL_PYMTAMT_ACTINFO',
'COLL_PYMTDT_RETURNINFO',
'DUEDATEHISTORY',
'TRIADHISTORY',
'CUSTOMER_DATA_MASTER',
'ACCOUNT',
'SUBSIDY_DETAILS',
'CHUB_LINE_COLLECT',
'PRODUCT_CODE',
'PRODUCT_CODE_REF',
'CUSTOMER_DATA_STAGING'
)
AND TABLE_OWNER='CDE';
=========================================================================================================================================
SELECT OWNER, TABLE_NAME, LAST_ANALYZED, STALE_STATS as "STALE" FROM DBA_TAB_STATISTICS WHERE TABLE_NAME IN (
'STG_BAN_EVENTS',
'TU_CREDIT_SCORE',
'DATA_QUALITY_METRICS',
'BUSINESS_METRICS',
'IOT_PRODUCTS',
'IOT_ONGOING_AMOUNT',
'VW_IOT_PRODUCTS',
'IOT_PRODUCTS_LINES',
'IOT_AGREEMENT_UPDATED',
'COLL_PYMTAMT_ACTINFO',
'COLL_PYMTDT_RETURNINFO',
'DUEDATEHISTORY',
'TRIADHISTORY',
'CUSTOMER_DATA_MASTER',
'ACCOUNT',
'SUBSIDY_DETAILS',
'CHUB_LINE_COLLECT',
'PRODUCT_CODE',
'PRODUCT_CODE_REF',
'CUSTOMER_DATA_STAGING'
)
AND OWNER='CDE'
ORDER BY LAST_ANALYZED DESC;
=========================================================================================================================================
SET HEADING OFF
SELECT 'EXECUTE DBMS_STATS.GATHER_TABLE_STATS(OWNNAME=>''CDE'',TABNAME=>'''||TABLE_NAME||''',ESTIMATE_PERCENT=>DBMS_STATS.AUTO_SAMPLE_SIZE,METHOD_OPT=>''FOR ALL COLUMNS SIZE AUTO'',NO_INVALIDATE=>TRUE,CASCADE=>TRUE,DEGREE=>4);'  
FROM DBA_TAB_STATISTICS 
WHERE STALE_STATS <> 'NO' 
AND TABLE_NAME IN (
'STG_BAN_EVENTS',
'TU_CREDIT_SCORE',
'DATA_QUALITY_METRICS',
'BUSINESS_METRICS',
'IOT_PRODUCTS',
'IOT_ONGOING_AMOUNT',
'VW_IOT_PRODUCTS',
'IOT_PRODUCTS_LINES',
'IOT_AGREEMENT_UPDATED',
'COLL_PYMTAMT_ACTINFO',
'COLL_PYMTDT_RETURNINFO',
'DUEDATEHISTORY',
'TRIADHISTORY',
'CUSTOMER_DATA_MASTER',
'ACCOUNT',
'SUBSIDY_DETAILS',
'CHUB_LINE_COLLECT',
'PRODUCT_CODE',
'PRODUCT_CODE_REF',
'CUSTOMER_DATA_STAGING'
)
AND OWNER='CDE';
=========================================================================================================================================
SET HEADING ON
SELECT OWNER, TABLE_NAME, LAST_ANALYZED, STALE_STATS as "STALE" FROM DBA_TAB_STATISTICS WHERE TABLE_NAME IN (
'STG_BAN_EVENTS',
'TU_CREDIT_SCORE',
'DATA_QUALITY_METRICS',
'BUSINESS_METRICS',
'IOT_PRODUCTS',
'IOT_ONGOING_AMOUNT',
'VW_IOT_PRODUCTS',
'IOT_PRODUCTS_LINES',
'IOT_AGREEMENT_UPDATED',
'COLL_PYMTAMT_ACTINFO',
'COLL_PYMTDT_RETURNINFO',
'DUEDATEHISTORY',
'TRIADHISTORY',
'CUSTOMER_DATA_MASTER',
'ACCOUNT',
'SUBSIDY_DETAILS',
'CHUB_LINE_COLLECT',
'PRODUCT_CODE',
'PRODUCT_CODE_REF',
'CUSTOMER_DATA_STAGING'
)
AND OWNER='CDE'
ORDER BY LAST_ANALYZED DESC;
=========================================================================================================================================
spool off;
=========================================================================================================================================

EXECUTE DBMS_STATS.GATHER_TABLE_STATS(OWNNAME=>'CDE',TABNAME=>'STG_BAN_EVENTS',ESTIMATE_PERCENT=>DBMS_STATS.AUTO_SAMPLE_SIZE,METHOD_OPT=>'FOR ALL COLUMNS SIZE AUTO',NO_INVALIDATE=>TRUE,CASCADE=>TRUE,DEGREE=>4);



exec dbms_stats.gather_table_stats(ownname=>'IBM',tabname=>'dm_sku_partition_stg',GRANULARITY => 'PARTITION',estimate_percent=>dbms_stats.auto_sample_size,cascade=>true);
Or
2. exec dbms_stats.gather_table_stats(ownname=>'IBM',tabname=>'dm_sku_partition_stg',GRANULARITY=>'GLOBAL AND PARTITION',estimate_percent=>dbms_stats.auto_sample_size,cascade=>true,degree=>8);