PROMPT Coleta Informacoes
PROMPT DBA: Rafael Oliveira
PROMPT Arquivo: COLETA_DB_$SID_ORACLE1.sql

ALTER SESSION SET NLS_DATE_FORMAT='dd/mm/yyyy hh24:mi:ss';

COLUMN NAME1 NEW_VALUE SID_ORACLE1 NOPRINT
SELECT NAME NAME1 FROM V$DATABASE;

COLUMN NAME2 NEW_VALUE SID_ORACLE2 NOPRINT
SELECT NAME||'.HTML' NAME2 FROM V$DATABASE;

SET LONG 100000000
SET PAGESIZE 49999
SET FEEDBACK OFF

SET MARKUP HTML ON SPOOL ON PREFORMAT OFF ENTMAP ON -
HEAD "<TITLE>** Relatorio Consultoria **</TITLE> -
<STYLE type='text/css'> <!-- BODY {font:10pt Arial,Helvetica,sans-serif; color:black; background:White;} p {font:10pt Arial,Helvetica,sans-serif; color:black; background:White;} table,tr,td {font:10pt Arial,Helvetica,sans-serif; color:Black; background:#f7f7e7; padding:0px 0px 0px 0px; margin:0px 0px 0px 0px;} th {font:bold 10pt Arial,Helvetica,sans-serif; color:#336699; background:#cccc99; padding:0px 0px 0px 0px;} h1 {font:16pt Arial,Helvetica,Geneva,sans-serif; color:#336699; background-color:White; border-bottom:1px solid #cccc99; margin-top:0pt; margin-bottom:0pt; padding:0px 0px 0px 0px;-
} h2 {font:bold 10pt Arial,Helvetica,Geneva,sans-serif; color:#336699; background-color:White; margin-top:4pt; margin-bottom:0pt;} a {font:9pt Arial,Helvetica,sans-serif; color:#663300; background:#ffffff; margin-top:0pt; margin-bottom:0pt; vertical-align:top;} --> -</STYLE>" -
BODY "TEXT='#0404B4'" -
TABLE "WIDTH='80%' ALIGN='center' BORDER='1'"

SPOOL RELATORIO_&SID_ORACLE2

TTITLE CENTER 'RELATORIO CONSULTORIA - ' SID_ORACLE1 SKIP CENTER ' '

TTITLE CENTER 'INFORMACOES INSTANCIA ' SID_ORACLE1 SKIP CENTER ' '
SELECT INSTANCE_NUMBER "INSTANCE_NUMBER", INSTANCE_NAME "INSTANCE_NAME", HOST_NAME "HOST_NAME", STARTUP_TIME,STATUS "STARTUP_TIME"
FROM V$INSTANCE;

TTITLE CENTER 'VERSAO BANCO DE DADOS ' SID_ORACLE1 SKIP CENTER ' '
SELECT BANNER AS "INFORMACOES DATABASE" FROM V$VERSION;

TTITLE CENTER  'HITS DE MEMORIA ORACLE ' SID_ORACLE1 SKIP CENTER ' '
SET LINESIZE 400
COL "BUFFER HIT RATIO" FORMAT A16;
COL "DICTIONARY HIT RATIO" FORMAT A20;
COL "LIBRARY HIT RATIO" FORMAT A17;
COL "REDOLOG WAIT" FORMAT A12;
COL "PGA HIT RATIO" FORMAT A13;
WITH
A AS (SELECT TO_CHAR(ROUND(((1-(SUM(DECODE(NAME,'PHYSICAL READS',VALUE,0))/(SUM(DECODE(NAME,'DB BLOCK GETS',VALUE,0))+(SUM(DECODE(NAME,'CONSISTENT GETS',VALUE,0))))))*100),4),'99.99') || '%' AS "BUFFER HIT RATIO" FROM V$SYSSTAT),
B AS (SELECT TO_CHAR(ROUND(((1-(SUM(GETMISSES)/SUM(GETS)))*100),4),'999.99') || '%' AS "DICTIONARY HIT RATIO" FROM V$ROWCACHE),
C AS (SELECT TO_CHAR(ROUND(100-((((SUM(RELOADS)/SUM(PINS))))),4),'999.99') || '%' AS "LIBRARY HIT RATIO" FROM V$LIBRARYCACHE),
D AS (SELECT TO_CHAR(ROUND((100-(100*SUM(DECODE(NAME,'REDO LOG SPACE REQUESTS',VALUE,0))/SUM(DECODE(NAME,'REDO ENTRIES',VALUE,0)))),4),'999.999') || '%' AS "REDOLOG WAIT" FROM SYS.V_$SYSSTAT),
E AS (SELECT TO_CHAR(ROUND(VALUE,4),'999.99') ||'%' "PGA HIT RATIO" FROM SYS.V_$PGASTAT WHERE NAME = 'CACHE HIT PERCENTAGE')
SELECT * FROM A,B,C,D,E;

TTITLE CENTER BOLD 'SHARED POOL SIZE (EXECUTION MISSES) - DEVE ESTAR A MENOS DE 1% ' SID_ORACLE1 SKIP CENTER ' '
SET LINES 155
SET PAGESIZE 400
COLUMN "EXECUTIONS" FORMAT 999,999,999,999,999,990
COLUMN "CACHE MISSES EXECUTING" FORMAT 999,999,990
COLUMN "DATA DICTIONARY GETS" FORMAT 999,999,999,999,999
COLUMN "GET MISSES" FORMAT 999,999,999,999
SELECT SUM(PINS) "EXECUTIONS", SUM(RELOADS) "CACHE MISSES EXECUTING", (SUM(RELOADS)/SUM(PINS)*100) "%RATIO (STAY UNDER 1%)"--, --(SUM(PINHITS)/SUM(PINS)*100) "%RATIO LC"
FROM V$LIBRARYCACHE;

TTITLE CENTER BOLD 'SHARED POOL SIZE (DICTIONARY GETS) - DEVE ESTAR ABAIXO DE 12% ' SID_ORACLE1 SKIP CENTER ' '
SELECT SUM(GETS) "DATA DICTIONARY GETS", SUM(GETMISSES) "GET MISSES", 100*(SUM(GETMISSES)/SUM(GETS)) "%RATIO (STAY UNDER 12%)"
FROM V$ROWCACHE;

TTITLE CENTER 'INFORMACOES PARAMETROS ' SID_ORACLE1 SKIP CENTER ' '
SELECT NAME, VALUE
FROM V$PARAMETER
WHERE NAME IN ('SGA_MAX_SIZE','SGA_TARGET','MEMORY_MAX_TARGET','MEMORY_TARGET','PGA_AGGREGATE_TARGET','SHARED_POOL_SIZE','LARGE_POOL_SIZE','JAVA_POOL_SIZE','STREAMS_POOL_SIZE ');

TTITLE CENTER BOLD 'CONTROLFILE (TEM QUE ESTA MULTIPLEXADO)' SID_ORACLE1 SKIP CENTER ' '
SET LINES 155
COL NAME FOR A70
SELECT NAME, STATUS, IS_RECOVERY_DEST_FILE FROM V$CONTROLFILE;

TTITLE CENTER BOLD 'I/O - DATAFILE ' SID_ORACLE1 SKIP CENTER ' '
SET PAGES 100
SET LINES 100
COLUMN "COL1" FORMAT A75HEADING "NOME DO DATA FILE" WORD_WRAPPED
COLUMN "COL2" FORMAT 999,999,990 HEADING "BLOCOS      |FISICOS     "
COLUMN "COL3" FORMAT 999,999,990 HEADING "LEITURAS    |FISICAS     "
COLUMN "COL4" FORMAT 999,999,990 HEADING "GRAVACOES   |FISICAS     "
COLUMN "COL5" FORMAT 999,999,990 HEADING "TOTAL       |DE I/O      "
SELECT A.NAME "COL1", B.PHYBLKRD "COL2", B.PHYRDS "COL3", B.PHYWRTS "COL4", B.PHYRDS+B.PHYWRTS "COL5"
FROM V$DATAFILE A, V$FILESTAT B
WHERE A.FILE#=B.FILE#
ORDER BY 1;

TTITLE CENTER BOLD 'I/O - TEMPFILE ' SID_ORACLE1 SKIP CENTER ' '
COLUMN "COL1" FORMAT A75 HEADING "NOME DO TEMP FILE" WORD_WRAPPED
SELECT A.NAME "COL1", B.PHYBLKRD "COL2", B.PHYRDS "COL3", B.PHYWRTS "COL4", B.PHYRDS+B.PHYWRTS "COL5"
FROM V$TEMPFILE A, V$TEMPSTAT B
WHERE A.FILE#=B.FILE#
ORDER BY 1;

TTITLE CENTER BOLD 'REDO LOG BUFFER - WAIT ' SID_ORACLE1 SKIP CENTER ' '
SET LINES 155
SET PAGES 500
COLUMN "COL1" HEADING "EVENTO" FORMAT A50
COLUMN "COL2" HEADING "NUMERO ESPERAS" FORMAT 99,999,999,999
COLUMN "COL3" HEADING "MEDIA ESPERA (S)" FORMAT 99,999.90
SELECT EVENT "COL1", SUM(TOTAL_WAITS) "COL2", AVG(AVERAGE_WAIT)/100 "COL3"
FROM V$SYSTEM_EVENT
WHERE AVERAGE_WAIT > 0 AND EVENT IN ('LOG ARCHIVE I/O', 'LOG BUFFER SPACE', 'LOG FILE SYNC', 'LOG FILE PARALLEL WRITE', 'LOG FILE SEQUENTIAL READ', 'LOG FILE SINGLE WRITE', 'LOG FILE INIT WRITE', 'LOG FILE SWITCH (ARCHIVING NEEDED)', 'LOG FILE SWITCH (CHECKPOINT INCOMPLETE)', 'LOG FILE SWITCH (CLEARING LOG FILE)', 'LOG FILE SWITCH COMPLETION', 'LOG FILE SWITCH (PRIVATE STRAND FLUSH INCOMPLETE)', 'LOG SWITCH/ARCHIVE', 'LOG WRITE(EVEN)', 'LOG WRITE(ODD)')
GROUP BY EVENT
ORDER BY 3 DESC;

TTITLE CENTER BOLD 'REDO LOG ' SID_ORACLE1 SKIP CENTER ' '
SET LINES 155
COLUMN "COL1"  FORMAT 999 HEADING "GRUPO"
COLUMN "COL2"  FORMAT A37 HEADING "NOME DO MEMBRO"
COLUMN "COL3"  FORMAT A16 HEADING "STATUS"
COLUMN "COL4"  FORMAT A16 HEADING "ARCHIVED"
COLUMN "COL5"  FORMAT 999,999,999,999,999,999 HEADING "TAMANHO"
SELECT B.GROUP# "COL1", B.MEMBER "COL2", DECODE(B.STATUS,NULL,A.STATUS,B.STATUS||' '||A.STATUS) "COL3", A.ARCHIVED "COL4", A.BYTES "COL5"
FROM SYS.V$LOG A, SYS.V$LOGFILE B
WHERE A.GROUP# = B.GROUP#
ORDER BY B.GROUP#;

TTITLE CENTER BOLD 'TAMANHO BANCO DE DADOS ' SID_ORACLE1 SKIP CENTER ' '
SET PAGESIZE 50
SET LINESIZE 120
SET HEADING ON
COLUMN TABLESPACE_NAME HEADING 'TABLESPACE' JUSTIFY LEFT FORMAT A20 TRUNCATED
COLUMN TBSIZE HEADING 'SIZE|(MB) ' JUSTIFY LEFT FORMAT 9,999,999.99
COLUMN TBUSED HEADING 'USED|(MB) ' JUSTIFY RIGHT FORMAT 9,999,999.99
COLUMN TBFREE HEADING 'FREE|(MB) ' JUSTIFY RIGHT FORMAT 9,999,999.99
COLUMN TBUSEDPCT HEADING 'USED % ' JUSTIFY LEFT FORMAT A8
COLUMN TBFREEPCT HEADING 'FREE % ' JUSTIFY LEFT FORMAT A8
BREAK ON REPORT
COMPUTE SUM LABEL 'TOTALS:' OF TBSIZE TBUSED TBFREE ON REPORT
SELECT T.TABLESPACE_NAME, ROUND(A.BYTES,2) TBSIZE, NVL(ROUND(C.BYTES,2),'0') TBFREE, NVL(ROUND(B.BYTES,2),'0') TBUSED, TO_CHAR(ROUND(100 * (NVL(B.BYTES,0)/NVL(A.BYTES,1)),2)) || '%' TBUSEDPCT, TO_CHAR(ROUND(100 * (NVL(C.BYTES,0)/NVL(A.BYTES,1)),2)) || '%' TBFREEPCT
FROM DBA_TABLESPACES T,
(SELECT TABLESPACE_NAME, ROUND(SUM(BYTES)/1024/1024,2) BYTES FROM DBA_DATA_FILES GROUP BY TABLESPACE_NAME UNION
SELECT TABLESPACE_NAME, ROUND(SUM(BYTES)/1024/1024,2) BYTES FROM DBA_TEMP_FILES GROUP BY TABLESPACE_NAME ) A,
(SELECT E.TABLESPACE_NAME, ROUND(SUM(E.BYTES)/1024/1024,2) BYTES FROM DBA_SEGMENTS E GROUP BY E.TABLESPACE_NAME UNION
SELECT TABLESPACE_NAME, SUM(MAX_SIZE) BYTES FROM V$SORT_SEGMENT GROUP BY TABLESPACE_NAME) B,
(SELECT F.TABLESPACE_NAME, ROUND(SUM(F.BYTES)/1024/1024,2) BYTES FROM DBA_FREE_SPACE F GROUP BY F.TABLESPACE_NAME UNION
SELECT TMP.TABLESPACE_NAME, (SUM(BYTES/1024/1024) - SUM(MAX_SIZE)) BYTES FROM DBA_TEMP_FILES TMP, V$SORT_SEGMENT SORT WHERE TMP.TABLESPACE_NAME = SORT.TABLESPACE_NAME GROUP BY TMP.TABLESPACE_NAME) C
WHERE T.TABLESPACE_NAME = A.TABLESPACE_NAME (+) AND T.TABLESPACE_NAME = B.TABLESPACE_NAME (+) AND T.TABLESPACE_NAME = C.TABLESPACE_NAME (+)
ORDER BY T.TABLESPACE_NAME;

TTITLE CENTER BOLD 'TABLESPACE TAMANHO ' SID_ORACLE1 SKIP CENTER ' '
SELECT DF.TABLESPACE_NAME "TABLESPACE", (DF.TOTALSPACE - FS.FREESPACE) "USED MB", FS.FREESPACE "FREE MB", DF.TOTALSPACE "TOTAL MB", ROUND(100 * (FS.FREESPACE / DF.TOTALSPACE)) "PCT. FREE"
FROM
(SELECT TABLESPACE_NAME, ROUND(SUM(BYTES) / 1048576) TOTALSPACE FROM DBA_DATA_FILES GROUP BY TABLESPACE_NAME ) DF,
(SELECT TABLESPACE_NAME, ROUND(SUM(BYTES) / 1048576) FREESPACE FROM DBA_FREE_SPACE GROUP BY TABLESPACE_NAME ) FS
WHERE DF.TABLESPACE_NAME = FS.TABLESPACE_NAME(+)
ORDER BY 1;

TTITLE CENTER BOLD 'ESTATISTICA DE LIBRARY CACHE ' SID_ORACLE1 SKIP CENTER ' '
SET PAGESIZE 100
SELECT NAMESPACE "NAMESPACE", GETS "GETS", GETHITS "GETHITS", ROUND(GETHITRATIO*100,2) "GETHIT_RATIO", PINS "PINS", PINHITS "PINHITS", ROUND(PINHITRATIO*100,2) "PINHIT_RATIO", RELOADS "RELOADS", INVALIDATIONS "INVALIDATIONS"
FROM V$LIBRARYCACHE;

TTITLE CENTER BOLD 'ESTATISTICA DO DICIONARIO ' SID_ORACLE1 SKIP CENTER ' '
SET PAGESIZE 100
COLUMN PARAMETER FORMAT A21
COLUMN PCT_SUCC_GETS FORMAT 999.9
COLUMN UPDATES FORMAT 999,999,999
SELECT PARAMETER, SUM(GETS), SUM(GETMISSES), 100*SUM(GETS - GETMISSES) / SUM(GETS) PCT_SUCC_GETS, SUM(MODIFICATIONS) UPDATES
FROM V$ROWCACHE
WHERE GETS > 0
GROUP BY ROLLUP(PARAMETER);

TTITLE CENTER BOLD 'ESTATISTICA DO DICIONARIO "< 60%" ' SID_ORACLE1 SKIP CENTER ' '
COLUMN PARAMETER FORMAT A21
COLUMN PCT_SUCC_GETS FORMAT 999.9
COLUMN UPDATES FORMAT 999,999,999
SELECT PARAMETER, SUM(GETS), SUM(GETMISSES), TO_CHAR(100*SUM(GETS - GETMISSES) / SUM(GETS),'999D99') PCT_SUCC_GETS, SUM(MODIFICATIONS) UPDATES
FROM V$ROWCACHE
WHERE GETS > 0
GROUP BY ROLLUP(PARAMETER) HAVING 100*SUM(GETS - GETMISSES) / SUM(GETS) <= 60;

TTITLE CENTER BOLD 'LATCH HIT ' SID_ORACLE1 SKIP CENTER ' '
SET LINES 155
SET PAGESIZE 400
SELECT (1 - (SUM(MISSES) / SUM(GETS))) * 100 "LATCH HIT"
FROM V$LATCH;

TTITLE CENTER BOLD 'UTILIZACAO BUFFER CACHE ' SID_ORACLE1 SKIP CENTER ' '
SET LINES 80
COLUMN "COL1" FORMAT A25 HEADING "BLOCOS BUFFER CACHE"
COLUMN "COL2" FORMAT 99,999,999,990 HEADING "QUANTIDADE"
COLUMN "COL3" FORMAT 99,999,999,990 HEADING "TOTAL"
SELECT DECODE(STATE, 0,'NAO USADO', 1,'LIDO E MODIFICADO', 2,'LIDO E NAO MODIFICADO', 3,'LIDO CORRENTEMENTE', 'OUTROS')"COL1", COUNT(*) "COL2"
FROM X$BH
GROUP BY DECODE(STATE, 0,'NAO USADO', 1,'LIDO E MODIFICADO', 2,'LIDO E NAO MODIFICADO', 3,'LIDO CORRENTEMENTE', 'OUTROS');

TTITLE CENTER BOLD 'POOL LIVRE NA SGA ' SID_ORACLE1 SKIP CENTER ' '
COL MB_FREE FOR 999,999,999.999,999
SELECT INITCAP(POOL) POOL, BYTES/1024/1024 MB_FREE
FROM V$SGASTAT
WHERE NAME = 'FREE MEMORY'

TTITLE CENTER BOLD 'CONSULTA DETALHADA SGA ' SID_ORACLE1 SKIP CENTER ' '
SET PAGESIZE 100
SELECT NAME, MB AS MB_TOTAL, NVL(INUSE,0) AS MB_USED, ROUND(100 - ((NVL(INUSE,0) / MB) * 100),2) "PERC_MB_FREE" FROM (SELECT NAME, ROUND(SUM(MB),2) MB, ROUND(SUM(INUSE),2) INUSE FROM (SELECT CASE WHEN NAME = 'BUFFER_CACHE' THEN 'BUFFER CACHE' WHEN NAME = 'LOG_BUFFER' THEN 'LOG BUFFER' ELSE POOL END NAME,  BYTES/1024/1024 MB, CASE WHEN NAME = 'BUFFER_CACHE' THEN (BYTES - (SELECT COUNT(*) FROM V$BH WHERE STATUS='FREE') * (SELECT VALUE FROM V$PARAMETER WHERE NAME = 'DB_BLOCK_SIZE') )/1024/1024 WHEN NAME <> 'FREE MEMORY' THEN BYTES/1024/1024 END INUSE FROM V$SGASTAT) WHERE NAME IS NOT NULL GROUP BY  NAME) UNION ALL SELECT 'SGA', ROUND(SUM(BYTES)/1024/1024,2), (ROUND(SUM(BYTES)/1024/1024,2)) - ROUND(SUM(DECODE(NAME,'FREE MEMORY',BYTES,0))/1024/1024,2), ROUND((SUM(DECODE(NAME,'FREE MEMORY',BYTES,0))/SUM(BYTES))*100,2)
FROM V$SGASTAT;

TTITLE CENTER BOLD 'PARSE ' SID_ORACLE1 SKIP CENTER ' '
SET LINES 155
SELECT TO_CHAR(100 * SESS / CALLS, '999999999990.00') || '%' CURSOR_CACHE_HITS, TO_CHAR(100 * (CALLS - SESS - HARD) / CALLS, '999990.00') || '%' SOFT_PARSES, TO_CHAR(100 * HARD / CALLS, '999990.00') || '%' HARD_PARSES
FROM
(SELECT VALUE CALLS FROM V$SYSSTAT WHERE NAME = 'PARSE COUNT (TOTAL)'),
(SELECT VALUE HARD FROM V$SYSSTAT WHERE NAME = 'PARSE COUNT (HARD)'),
(SELECT VALUE SESS FROM V$SYSSTAT WHERE NAME = 'SESSION CURSOR CACHE HITS');

TTITLE CENTER BOLD 'UTILIZACAO PGA ' SID_ORACLE1 SKIP CENTER ' '
COLUMN "COL1"  FORMAT 999,999,999,999,999,990 HEADING "PGA USADA CORRENTEMENTE"
COLUMN "COL2"  FORMAT 999,999,999,999,999,990 HEADING "PGA ALOCADA CORRENTEMENTE"
COLUMN "COL3"  FORMAT 999,999,999,999,999,990 HEADING "PGA MAXIMA ALOCADA"
SELECT SUM (PGA_USED_MEM) "COL1", SUM (PGA_ALLOC_MEM) "COL2", SUM (PGA_MAX_MEM) "COL3"
FROM V$PROCESS;

TTITLE CENTER BOLD 'ESTATISTICA - UTILIZACAO DE MEMORIA ' SID_ORACLE1 SKIP CENTER ' '
COLUMN "COL1"  FORMAT A35  	    HEADING "ESTATISTICA"
COLUMN "COL2"  FORMAT 999,999,999,999,999,990 HEADING "VALOR"
SELECT NAME "COL1", VALUE "COL2"
FROM V$SYSSTAT
WHERE NAME LIKE '%WORKAREA%';

TTITLE CENTER BOLD 'WORKAREA COM MAIOR CONSUMO DE MEMORIA ' SID_ORACLE1 SKIP CENTER ' '
SET LINES 155
SET PAGESIZE 100
COLUMN "COL1" FORMAT 999999999 HEADING "WORKAREA"
COLUMN "COL2" FORMAT A18 HEADING "OPERACAO"
COLUMN "COL3" FORMAT A6 HEADING "POLIT."
COLUMN "COL4" FORMAT 999,999,999,999,999 HEADING "TAMANHO EM KB|PARA EXECUCAO|EM MEMORIA"
COLUMN "COL5" FORMAT 99,999 HEADING "NRO DE|VEZES|FICOU|ATIVA"
COLUMN "COL6" FORMAT 99,999 HEADING "NRO DE|VEZES|RODOU|OPTIMAL"
COLUMN "COL7" FORMAT 99,999 HEADING "NRO DE|VEZES|RODOU|ONE-PASS"
COLUMN "COL8" FORMAT 99,999 HEADING "NRO DE|VEZES|RODOU|MULTI-PASS"
COLUMN "COL9" FORMAT 999,999,999,999,999,999 HEADING "MEDIA|TEMPO|ATIVA|CENT/SEGS"
SELECT *
FROM (SELECT WORKAREA_ADDRESS "COL1", OPERATION_TYPE "COL2", POLICY "COL3", ESTIMATED_OPTIMAL_SIZE "COL4", TOTAL_EXECUTIONS "COL5", OPTIMAL_EXECUTIONS "COL6", ONEPASS_EXECUTIONS "COL7", MULTIPASSES_EXECUTIONS "COL8", ACTIVE_TIME "COL9" FROM V$SQL_WORKAREA ORDER BY ESTIMATED_OPTIMAL_SIZE DESC)
WHERE ROWNUM <= 10;

TTITLE CENTER BOLD 'ADVISORS ' SID_ORACLE1 SKIP CENTER ' '
SET LINES 400;
SET PAGESIZE 100
SELECT SIZE_FOR_ESTIMATE, SIZE_FACTOR, ESTD_PHYSICAL_READ_FACTOR
FROM V$DB_CACHE_ADVICE
ORDER BY 1;

TTITLE CENTER BOLD 'SHARED POOL ADVISORS ' SID_ORACLE1 SKIP CENTER ' '
SET PAGESIZE 100
SELECT SHARED_POOL_SIZE_FOR_ESTIMATE, SHARED_POOL_SIZE_FACTOR, ESTD_LC_TIME_SAVED, ESTD_LC_SIZE
FROM V$SHARED_POOL_ADVICE
ORDER BY 1;

TTITLE CENTER BOLD 'PGA ADVISORS ' SID_ORACLE1 SKIP CENTER ' '
SET PAGESIZE 100
SELECT PGA_TARGET_FACTOR, PGA_TARGET_FOR_ESTIMATE, ESTD_PGA_CACHE_HIT_PERCENTAGE, ESTD_EXTRA_BYTES_RW
FROM V$PGA_TARGET_ADVICE
ORDER BY 1;

TTITLE CENTER BOLD 'SGA TARGET ADVISORS ' SID_ORACLE1 SKIP CENTER ' '
SET PAGESIZE 100
SELECT *
FROM V$SGA_TARGET_ADVICE
ORDER BY SGA_SIZE;

TTITLE CENTER BOLD 'MEMORY TARGET ADVISORS ' SID_ORACLE1 SKIP CENTER ' '
SET PAGESIZE 100
SELECT *
FROM V$MEMORY_TARGET_ADVICE
ORDER BY MEMORY_SIZE;

TTITLE CENTER BOLD 'SORT ' SID_ORACLE1 SKIP CENTER ' '
SET LINES 80
SET PAGESIZE 100
COLUMN "COL1" FORMAT A70
SELECT INITCAP(RPAD(NAME,30,' ')||' = '|| RPAD(TO_CHAR(VALUE,'999,999,999,999,999,990'),30,' ')) "COL1"
FROM V$SYSSTAT
WHERE NAME IN ('SORTS (MEMORY)','SORTS (DISK)');

TTITLE CENTER BOLD 'CHECKPOINT / DATAFILE HEADERG ' SID_ORACLE1 SKIP CENTER ' '
SELECT STATUS, CHECKPOINT_CHANGE#, FUZZY, TO_CHAR(CHECKPOINT_TIME, 'DD-MM-YYYY HH24:MI:SS') AS CHECKPOINT_TIME, COUNT(*)
FROM V$DATAFILE_HEADER
GROUP BY STATUS, CHECKPOINT_CHANGE#, FUZZY, CHECKPOINT_TIME
ORDER BY STATUS, CHECKPOINT_CHANGE#, FUZZY, CHECKPOINT_TIME;

TTITLE CENTER BOLD 'EVENTOS ' SID_ORACLE1 SKIP CENTER ' '
SET LINES 80
SET PAGES 500
SET PAGESIZE 100
COLUMN "COL1" HEADING "EVENTO" FORMAT A30
COLUMN "COL2" HEADING "NUMERO DE ESPERAS" FORMAT 99,999,999,999
COLUMN "COL3" HEADING "MEDIA DE ESPERA" FORMAT 99,999.90
SELECT SUBSTR(EVENT,1,30) "COL1", SUM(TOTAL_WAITS) "COL2", AVG(AVERAGE_WAIT)/100 "COL3"
FROM V$SYSTEM_EVENT
WHERE AVERAGE_WAIT > 0
GROUP BY EVENT
ORDER BY 3 DESC;

TTITLE CENTER BOLD 'FEATURES UTILIZADAS ' SID_ORACLE1 SKIP CENTER ' '
COL NAME FOR A60
SET PAGESIZE 100
SET LINES 155
SELECT NAME, DETECTED_USAGES, CURRENTLY_USED, FIRST_USAGE_DATE, LAST_USAGE_DATE
FROM DBA_FEATURE_USAGE_STATISTICS
WHERE DETECTED_USAGES > 0;

TTITLE CENTER BOLD 'OPTIONS ' SID_ORACLE1 SKIP CENTER ' '
COL PARAMETER FOR A65
SET PAGESIZE 100
SET LINES 155
SELECT PARAMETER, VALUE
FROM V$OPTION
ORDER BY 2,1;

TTITLE CENTER BOLD 'PERMITIR GERAR RELATORIO AWR ' SID_ORACLE1 SKIP CENTER ' '
SHOW PARAMETER CONTROL_MANAGEMENT_PACK_ACCESS

TTITLE CENTER BOLD 'AWR UTILIZADO ' SID_ORACLE1 SKIP CENTER ' '
SELECT NAME, DETECTED_USAGES, CURRENTLY_USED,
TO_CHAR(LAST_SAMPLE_DATE,'DD-MON-YYYY:HH24:MI') LAST_SAMPLE
FROM DBA_FEATURE_USAGE_STATISTICS
WHERE NAME = 'AWR REPORT';

TTITLE CENTER BOLD 'OBJETOS INVALIDOS - RESUMO ' SID_ORACLE1 SKIP CENTER ' '
SET LINES 155
COLUMN "COL1" FORMAT A25 HEADING "SCHEMA"
COLUMN "COL2" FORMAT A30 HEADING "OBJECT TYPE"
COLUMN "COL3" FORMAT A16 HEADING "STATUS"
COLUMN "COL4" FORMAT 999999999 HEADING "NUM OBJETOS INVALIDOS"
SELECT OWNER "COL1", OBJECT_TYPE "COL2", STATUS "COL3", COUNT(*) "COL4"
FROM DBA_OBJECTS
WHERE STATUS = 'INVALID'
GROUP BY OWNER,OBJECT_TYPE,STATUS
ORDER BY 1,2;

TTITLE CENTER BOLD 'OBJETOS INVALIDOS - DETALHADO ' SID_ORACLE1 SKIP CENTER ' '
SET PAGESIZE 1000
SET LINESIZE 300
SELECT OWNER, OBJECT_TYPE, OBJECT_NAME, STATUS
FROM DBA_OBJECTS
WHERE STATUS='INVALID'
ORDER BY 1,2;

TTITLE CENTER BOLD 'QUANTIDADES DE TABELAS (NUM_ROWS < 900) SEM ESTATISTICAS A 03 DIAS ' SID_ORACLE1 SKIP CENTER ' '
SET LINES 155
SET PAGESIZE 5000
SELECT OWNER AS SCHEMA, COUNT(*) AS QTD_TABABELAS
FROM DBA_TAB_STATISTICS
WHERE LAST_ANALYZED < SYSDATE - 3 AND NUM_ROWS < 900
GROUP BY OWNER
ORDER BY 1,2;

TTITLE CENTER BOLD 'TABELAS SEM COLETA DE ESTATISTICAS A 03 DIAS ' SID_ORACLE1 SKIP CENTER ' '
SET LINES 155
SET PAGESIZE 5000
SELECT OWNER,TABLE_NAME,NUM_ROWS,LAST_ANALYZED
FROM DBA_TAB_STATISTICS
WHERE LAST_ANALYZED < SYSDATE - 3 AND NUM_ROWS >= 900
ORDER BY 1,3;

TTITLE CENTER BOLD 'RECYCLEBIN ' SID_ORACLE1 SKIP CENTER ' '
COLUMN "COL1" FORMAT A10 HEADING "USUARIO"
COLUMN "COL2" FORMAT A35 HEADING "NOME OBJETO"
COLUMN "COL3" FORMAT A26 HEADING "NOME ORIGINAL"
COLUMN "COL4" FORMAT A14 HEADING "TIPO"
COLUMN "COL5" FORMAT A15 HEADING "TABLESPACE"
COLUMN "COL7" FORMAT A20 HEADING "CRIACAO"
COLUMN "COL8" FORMAT A20 HEADING "DROP"
SELECT OWNER "COL1", OBJECT_NAME "COL2", ORIGINAL_NAME "COL3", TYPE "COL4", TS_NAME "COL5", SPACE "ESPACO", CREATETIME "COL7", DROPTIME "COL8"
FROM DBA_RECYCLEBIN;

TTITLE CENTER BOLD 'ROLE DBA ' SID_ORACLE1 SKIP CENTER ' '
SET LINESIZE 100
SET PAGES 1000
COLUMN "COL1" FORMAT A30 HEADING "USUARIO"
SELECT GRANTEE "COL1"
FROM DBA_ROLE_PRIVS
WHERE GRANTED_ROLE = 'DBA' AND GRANTEE NOT IN (SELECT ROLE FROM DBA_ROLES);

TTITLE CENTER BOLD 'ARCHIVE GERADO POR HORA ' SID_ORACLE1 SKIP CENTER ' '
ALTER SESSION SET NLS_DATE_FORMAT='DD/MM/YYYY HH24:MI:SS';

SELECT TRUNC(FIRST_TIME,'HH') DATA_HORA,COUNT(*) QTD, SUM(BLOCKS*BLOCK_SIZE/1024/1024) MB
FROM V$ARCHIVED_LOG
WHERE TO_CHAR(TRUNC(FIRST_TIME,'HH'),'YYYYMM') = TO_CHAR(SYSDATE-30,'YYYYMM')
GROUP BY TRUNC(FIRST_TIME,'HH')
ORDER BY TRUNC(FIRST_TIME,'HH');

TTITLE CENTER BOLD 'VOLUME DE ARCHIVE POR DIA ' SID_ORACLE1 SKIP CENTER ' '
COLUMN MB FORMAT 999,999,990.000
SELECT TRUNC(FIRST_TIME,'DD') HORARIO, SUM(BLOCKS*BLOCK_SIZE/1024/1024) MB
FROM V$ARCHIVED_LOG
GROUP BY TRUNC(FIRST_TIME,'DD')
ORDER BY 1;

TTITLE CENTER BOLD 'JOBS QUEBRADOS OU FALHADOS ' SID_ORACLE1 SKIP CENTER ' '
SET LINES 400
SET PAGES 1000
COL WHAT FOR A47
COL SCHEMA_USER FOR A20
SELECT SCHEMA_USER, JOB, BROKEN, FAILURES, WHAT
FROM DBA_JOBS
WHERE BROKEN='Y' OR FAILURES>0;

TTITLE CENTER BOLD 'RESOURCE LIMIT ' SID_ORACLE1 SKIP CENTER ' '
SET LINES 999 PAGES 1000
SELECT *
FROM V$RESOURCE_LIMIT
WHERE RESOURCE_NAME IN ('PROCESSES','SESSIONS','TRANSACTIONS','ENQUEUE_RESOURCES');

SPOOL OFF
SET MARKUP HTML OFF
EXIT
