DECLARE
L_PATH VARCHAR2(32767);
I INT;
BEGIN
SELECT SUBSTR(NAME, 1, INSTR(NAME, '/', -1)) PATH 
INTO L_PATH
FROM V$DATAFILE WHERE ROWNUM < 2;

EXECUTE IMMEDIATE 'CREATE TABLESPACE READ_ONLY DATAFILE ''' || L_PATH || 'READ_ONLY01.DBF'' SIZE 1M AUTOEXTEND ON NEXT 1M MAXSIZE 10M';
EXECUTE IMMEDIATE 'ALTER USER HR QUOTA UNLIMITED ON READ_ONLY';
EXECUTE IMMEDIATE 'CREATE TABLE HR.TEST_RO_TABLE (A NUMBER) TABLESPACE READ_ONLY';
FOR I IN 1 .. 5
LOOP
EXECUTE IMMEDIATE 'INSERT INTO HR.TEST_RO_TABLE VALUES (:A)' USING I;
END LOOP;
EXECUTE IMMEDIATE 'ALTER TABLESPACE READ_ONLY READ ONLY';
END;
/
EXIT
