SET LINES 300
COL DB_LINK FORMAT A10
COL USERNAME FORMAT A20
COL HOST FORMAT A30
SELECT DB_LINK,USERNAME,HOST FROM DBA_DB_LINKS;


SET LINESIZE 500
SET PAGESIZE 1000
COL DB_LINK FOR A40
COL HOST FOR A20
SELECT OWNER, DB_LINK, USERNAME, HOST,
TO_CHAR(CREATED,’MM/DD/YYYY HH24:MI:SS’) CRIACAO
FROM DBA_DB_LINKS
ORDER BY OWNER, DB_LINK;