SET LINES 300
COL OWNER FOR A10
COL JOB_NAME FOR A20
COL ENAB FOR A5
COL JOB_TYPE FOR A15
COL JOB_ACTION FOR A50
COL START_DATE FOR A20
COL REPEAT_INTERVAL FOR A25
COL LAST_START_DATE FOR A20
COL NEXT_RUN_DATE FOR A20
COL "RUN" FOR 9999
COL "FAIL" FOR 9999
COL "RET" FOR 9999
SELECT OWNER, JOB_NAME, ENABLED as ENAB, JOB_TYPE, JOB_ACTION, to_char(START_DATE,'DD/MM/YYYY HH24:MI:SS') START_DATE, REPEAT_INTERVAL, to_char(LAST_START_DATE,'DD/MM/YYYY HH24:MI:SS') LAST_START_DATE, to_char(NEXT_RUN_DATE,'DD/MM/YYYY HH24:MI:SS') NEXT_RUN_DATE, RUN_COUNT "RUN",FAILURE_COUNT "FAIL", RETRY_COUNT "RET" FROM DBA_SCHEDULER_JOBS;


SELECT OWNER,OBJECT_NAME,OBJECT_TYPE,CREATED FROM DBA_OBJECTS WHERE OBJECT_NAME='PKG_PTU_BATCH' AND OBJECT_TYPE='PACKAGE';

--======================================================================

begin
dbms_scheduler.create_job (
   job_name           =>  'VALORIZAR_ESTOQUE_JOB',
   job_type           =>  'STORED_PROCEDURE',
   job_action         =>  'VALORIZAR_ESTOQUE',
   start_date         =>  '29-JAN-2020 12:00:00 AM',
   repeat_interval    =>  'FREQ=DAILY;BYHOUR=0',
   enabled            =>  TRUE);
END;
/


begin
dbms_scheduler.drop_job(job_name =>'VALORIZAR_ESTOQUE_JOB');
end;
/