SET HEADING OFF
SET FEEDBACK OFF
SET OFF PAGESIZE 0
SET VERIFY OFF
SET PAGESIZE 200
SET LINES 300
SPOOL /home/oracle/LIMPA_SCHEMA_DBO.sql
SELECT 'ALTER TABLE '||OWNER||'."'||TABLE_NAME||'" DROP CONSTRAINT "'||CONSTRAINT_NAME||'";' FROM DBA_CONSTRAINTS WHERE OWNER IN ('DBO') AND CONSTRAINT_TYPE = 'R'
/
 SELECT DISTINCT 'DROP SEQUENCE '||SEQUENCE_OWNER||'."'||SEQUENCE_NAME||'";' FROM DBA_SEQUENCES WHERE SEQUENCE_OWNER IN ('DBO')
/
 SELECT DISTINCT 'DROP '||TYPE||' '||OWNER||'."'||NAME||'";' FROM DBA_SOURCE WHERE OWNER IN ('DBO')
/
 SELECT 'DROP VIEW '||OWNER||'."'|| VIEW_NAME||'";' FROM DBA_VIEWS WHERE OWNER IN ('DBO')
/
 SELECT 'DROP TABLE '||OWNER||'."'||TABLE_NAME||'" PURGE;' FROM DBA_TABLES WHERE OWNER IN ('DBO')
/
 SELECT 'DROP SYNONYM '||OWNER||'."'||SYNONYM_NAME||'";' FROM DBA_SYNONYMS WHERE OWNER IN ('DBO')
/
 SELECT 'DROP TYPE '||OWNER||'."'||TYPE_NAME||'";' FROM DBA_TYPES WHERE OWNER IN ('DBO')
/
 SELECT 'DROP MATERIALIZED VIEW '||OWNER||'."'||MVIEW_NAME||'";' FROM DBA_MVIEWS WHERE OWNER IN ('DBO')
/
 SELECT 'DROP PUBLIC SYNONYM ' || SYNONYM_NAME || ';' FROM DBA_SYNONYMS WHERE TABLE_OWNER IN ('DBO') AND OWNER = 'PUBLIC' AND DB_LINK IS NULL ORDER BY SYNONYM_NAME
/
SET HEADING ON
SET FEEDBACK ON
SET VERIFY ON
SPOOL OFF

-- Checar objetos válidos e inválidos:
SET LINES 300
SET PAGESIZE 100
SET LONG 1
COL "OBJETOS DBO" FOR a40
SELECT DECODE (GROUPING(OBJECT_TYPE),1, 'xOBJETOS VALIDOS',OBJECT_TYPE) "OBJETOS DBO",STATUS, COUNT(*) "TOTAL" 
FROM DBA_OBJECTS WHERE OWNER='DBO' AND STATUS='VALID' GROUP BY rollup(OBJECT_TYPE),STATUS
UNION
SELECT DECODE (GROUPING(OBJECT_TYPE),1, 'xOBJETOS INVALIDOS',OBJECT_TYPE) "OBJETOS DBO",STATUS, COUNT(*) "TOTAL" 
FROM DBA_OBJECTS WHERE OWNER='DBO' AND STATUS='INVALID' GROUP BY rollup(OBJECT_TYPE),STATUS;

-- Checar total de objetos:
SET LINES 300
SET PAGESIZE 100
SET LONG 1
COL "OBJETOS DBO" FOR a40
SELECT DECODE (GROUPING(OBJECT_TYPE),1, 'xTOTAL OBJETOS',OBJECT_TYPE) "OBJETOS DBO", COUNT(*) "TOTAL" 
FROM DBA_OBJECTS WHERE OWNER in ('DBO') GROUP BY rollup(OBJECT_TYPE);

-- Checar total de objetos INVÁLIDOS:
SET LINES 300 
SET PAGESIZE 500
SELECT COUNT(*) 
FROM DBA_OBJECTS WHERE STATUS <> 'VALID';

-- Recompilar objetos:
EXEC UTL_RECOMP.RECOMP_SERIAL;