#!/bin/ksh

export ORAENV_ASK=NO

export ORACLE_HOME=/orasw/app/oracle/product/19/db
export ORACLE_SID=pcdep1
export PATH=/usr/bin:/etc:/usr/sbin:/usr/ucb:/usr/bin/X11:/sbin:/bin:/usr/local/bin:/opt/quest/bin:/opt/VRTS/bin:/usr/bin:/etc:/usr/sbin:/usr/ucb:/usr/bin/X11:/sbin:/usr/java8_64/jre/bin:/usr/java8_64/bin:/opt/quest/sbin:/opt/quest/bin:.:/orasw/app/oracle/product/19/db/bin:$ORACLE_HOME/bin:$PATH

. oraenv > /dev/null 2>&1

cd /orasw/static/oradba/bin/
$ORACLE_HOME/bin/sqlplus "/ as sysdba" <<EOF >> $LOGFILE

SET LINES 280 SERVEROUTPUT ON SIZE 1000000 ECHO ON TIME ON TIMING ON TRIM ON TRIMSPOOL ON UNDERLINE =
COL HOST_NAME FOR A20
COL OWNER FOR A20
COL TABLE_OWNER FOR A20
COL TABLE_NAME FOR A30
COL PARTITION_NAME FOR A20
COL SUBPARTITION_NAME FOR A20
SET TERMOUT OFF
COLUMN today_col NEW_VALUE today
SELECT TO_CHAR (SYSDATE, 'YYYYMMDD') AS today_col FROM dual;
SET TERMOUT ON
SPOOL 'cde_gather_table_stats_&today..log'

ALTER SESSION SET NLS_DATE_FORMAT='DD-MON-YYYY HH24:MI:SS';

SELECT INSTANCE_NAME, HOST_NAME, SYSDATE FROM V$INSTANCE;

SELECT * FROM DBA_TAB_MODIFICATIONS WHERE TABLE_NAME IN ('STG_BAN_EVENTS', 'TU_CREDIT_SCORE', 'DATA_QUALITY_METRICS', 'BUSINESS_METRICS', 'IOT_PRODUCTS', 'IOT_ONGOING_AMOUNT', 'VW_IOT_PRODUCTS', 'IOT_PRODUCTS_LINES', 'IOT_AGREEMENT_UPDATED', 'COLL_PYMTAMT_ACTINFO', 'COLL_PYMTDT_RETURNINFO', 'DUEDATEHISTORY', 'TRIADHISTORY', 'CUSTOMER_DATA_MASTER', 'ACCOUNT', 'SUBSIDY_DETAILS', 'CHUB_LINE_COLLECT', 'PRODUCT_CODE', 'PRODUCT_CODE_REF', 'CUSTOMER_DATA_STAGING') AND TABLE_OWNER='CDE';

SELECT OWNER, TABLE_NAME, LAST_ANALYZED, STALE_STATS as "STALE" FROM DBA_TAB_STATISTICS WHERE TABLE_NAME IN ('STG_BAN_EVENTS', 'TU_CREDIT_SCORE', 'DATA_QUALITY_METRICS', 'BUSINESS_METRICS', 'IOT_PRODUCTS', 'IOT_ONGOING_AMOUNT', 'VW_IOT_PRODUCTS', 'IOT_PRODUCTS_LINES', 'IOT_AGREEMENT_UPDATED', 'COLL_PYMTAMT_ACTINFO', 'COLL_PYMTDT_RETURNINFO', 'DUEDATEHISTORY', 'TRIADHISTORY', 'CUSTOMER_DATA_MASTER', 'ACCOUNT', 'SUBSIDY_DETAILS', 'CHUB_LINE_COLLECT', 'PRODUCT_CODE', 'PRODUCT_CODE_REF', 'CUSTOMER_DATA_STAGING') AND OWNER='CDE' ORDER BY LAST_ANALYZED DESC;

BEGIN
        dbms_output.put_line(to_char(sysdate, 'yyyy-mm-dd hh24:mi:ss'));

        FOR cUser IN (SELECT OWNER,TABLE_NAME FROM DBA_TAB_STATISTICS WHERE STALE_STATS <> 'NO' AND OWNER='CDE' AND TABLE_NAME IN ('STG_BAN_EVENTS', 'TU_CREDIT_SCORE', 'DATA_QUALITY_METRICS', 'BUSINESS_METRICS', 'IOT_PRODUCTS', 'IOT_ONGOING_AMOUNT', 'VW_IOT_PRODUCTS', 'IOT_PRODUCTS_LINES', 'IOT_AGREEMENT_UPDATED', 'COLL_PYMTAMT_ACTINFO', 'COLL_PYMTDT_RETURNINFO', 'DUEDATEHISTORY', 'TRIADHISTORY', 'CUSTOMER_DATA_MASTER', 'ACCOUNT', 'SUBSIDY_DETAILS', 'CHUB_LINE_COLLECT', 'PRODUCT_CODE', 'PRODUCT_CODE_REF', 'CUSTOMER_DATA_STAGING');) LOOP

                EXECUTE IMMEDIATE 'EXECUTE DBMS_STATS.GATHER_TABLE_STATS(OWNNAME=>''cUser.OWNER'', TABNAME=>'''||cUser.TABLE_NAME||''', ESTIMATE_PERCENT=>DBMS_STATS.AUTO_SAMPLE_SIZE, METHOD_OPT=>''FOR ALL COLUMNS SIZE AUTO'', NO_INVALIDATE=>TRUE, CASCADE=>TRUE, DEGREE=>4)';
                dbms_output.put_line('EXECUTE DBMS_STATS.GATHER_TABLE_STATS(OWNNAME=>''cUser.OWNER'', TABNAME=>'''||cUser.TABLE_NAME||''', ESTIMATE_PERCENT=>DBMS_STATS.AUTO_SAMPLE_SIZE, METHOD_OPT=>''FOR ALL COLUMNS SIZE AUTO'', NO_INVALIDATE=>TRUE, CASCADE=>TRUE, DEGREE=>4)');
        END LOOP;
END;

SELECT OWNER, TABLE_NAME, LAST_ANALYZED, STALE_STATS as "STALE" FROM DBA_TAB_STATISTICS WHERE TABLE_NAME IN ('STG_BAN_EVENTS', 'TU_CREDIT_SCORE', 'DATA_QUALITY_METRICS', 'BUSINESS_METRICS', 'IOT_PRODUCTS', 'IOT_ONGOING_AMOUNT', 'VW_IOT_PRODUCTS', 'IOT_PRODUCTS_LINES', 'IOT_AGREEMENT_UPDATED', 'COLL_PYMTAMT_ACTINFO', 'COLL_PYMTDT_RETURNINFO', 'DUEDATEHISTORY', 'TRIADHISTORY', 'CUSTOMER_DATA_MASTER', 'ACCOUNT', 'SUBSIDY_DETAILS', 'CHUB_LINE_COLLECT', 'PRODUCT_CODE', 'PRODUCT_CODE_REF', 'CUSTOMER_DATA_STAGING') AND OWNER='CDE' ORDER BY LAST_ANALYZED DESC;

quit
EOF

uuencode cde_gather_table_stats_`date +%Y%m%d`.log cde_gather_table_stats_`date +%Y%m%d`.log | mailx -s "CDES - Gather Table Stats" CFS-Coll-Ops@T-Mobile.com TEQDatabaseEngineering-Oracle-Prod@T-Mobile.com