-- GRANTS DE SESSÃO
GRANT CONNECT,RESOURCE,UNLIMITED TABLESPACE,CREATE SESSION TO BI;


-- GRANTS ON TABLES (SELECT,DELETE,UPDATE,INSERT,ALTER)
BEGIN
	FOR T IN (SELECT TABLE_NAME FROM DBA_TABLES WHERE OWNER='METADADOS' AND TABLE_NAME NOT IN (SELECT TABLE_NAME FROM DBA_TAB_PRIVS WHERE GRANTEE='BI')) LOOP   
		EXECUTE IMMEDIATE 'GRANT SELECT ON METADADOS.' || T.TABLE_NAME || ' TO BI';    
	END LOOP;
END;
/

-- GRANTS ON VIEWS (SELECT,DELETE,UPDATE,INSERT)
BEGIN
	FOR T IN (SELECT VIEW_NAME FROM DBA_VIEWS WHERE OWNER='METADADOS' AND VIEW_NAME NOT IN (SELECT TABLE_NAME FROM DBA_TAB_PRIVS WHERE GRANTEE='BI')) LOOP   
		EXECUTE IMMEDIATE 'GRANT SELECT ON METADADOS.' || T.VIEW_NAME || ' TO BI';    
	END LOOP;
END;
/

-- GRANTS ON FUNCTIONS (ALTER, CREATE, DROP, EXECUTE)
BEGIN
	FOR T IN (SELECT OBJECT_NAME FROM DBA_OBJECTS WHERE OWNER='METADADOS' AND OBJECT_TYPE='FUNCTION' AND OBJECT_NAME NOT IN (SELECT TABLE_NAME FROM DBA_TAB_PRIVS WHERE GRANTEE='BI')) LOOP   
		EXECUTE IMMEDIATE 'GRANT EXECUTE ON METADADOS.' || T.OBJECT_NAME || ' TO BI';    
	END LOOP;
END;
/

-- GRANTS ON PROCEDURES (ALTER, CREATE, DROP, EXECUTE)
BEGIN
	FOR T IN (SELECT OBJECT_NAME FROM DBA_OBJECTS WHERE OWNER='METADADOS' AND OBJECT_TYPE='PROCEDURE' AND OBJECT_NAME NOT IN (SELECT TABLE_NAME FROM DBA_TAB_PRIVS WHERE GRANTEE='BI')) LOOP   
		EXECUTE IMMEDIATE 'GRANT EXECUTE ON METADADOS.' || T.OBJECT_NAME || ' TO BI';    
	END LOOP;
END;
/

-- GRANTS ON PACKAGES (ALTER, CREATE, DROP, EXECUTE)
BEGIN
	FOR T IN (SELECT OBJECT_NAME FROM DBA_OBJECTS WHERE OWNER='METADADOS' AND OBJECT_TYPE='PACKAGE' AND OBJECT_NAME NOT IN (SELECT TABLE_NAME FROM DBA_TAB_PRIVS WHERE GRANTEE='BI')) LOOP   
		EXECUTE IMMEDIATE 'GRANT EXECUTE ON METADADOS.' || T.OBJECT_NAME || ' TO BI';    
	END LOOP;
END;
/

-- GRANTS ON TRIGGERS (ALTER, CREATE, DROP)
BEGIN
	FOR T IN (SELECT TRIGGER_NAME FROM DBA_TRIGGERS WHERE OWNER='METADADOS' AND TRIGGER_NAME NOT IN (SELECT TABLE_NAME AS VIEW_NAME FROM DBA_TAB_PRIVS WHERE GRANTEE='BI')) LOOP   
		EXECUTE IMMEDIATE 'GRANT EXECUTE ON METADADOS.' || T.TRIGGER_NAME || ' TO DBAINDYXA,DBANOX,DBAHB,DBAINT';    
	END LOOP;
END;
/

-- GRANTS ON SEQUENCES (ALTER, CREATE, DROP, SELECT)
BEGIN
	FOR T IN (SELECT SEQUENCE_NAME FROM DBA_SEQUENCES WHERE SEQUENCE_OWNER='METADADOS' AND SEQUENCE_NAME NOT IN (SELECT TABLE_NAME AS VIEW_NAME FROM DBA_TAB_PRIVS WHERE GRANTEE='BI')) LOOP   
		EXECUTE IMMEDIATE 'GRANT SELECT,ALTER ON METADADOS.' || T.SEQUENCE_NAME || ' TO BI';    
	END LOOP;
END;
/

-- GRANTS PUBLIC SYNONYMS [tables] (ALTER, CREATE, DROP)
BEGIN
	FOR R IN (SELECT TABLE_NAME FROM DBA_TABLES WHERE OWNER='METADADOS' AND TABLE_NAME NOT IN (SELECT SYNONYM_NAME FROM DBA_SYNONYMS WHERE OWNER='PUBLIC')) LOOP
		EXECUTE IMMEDIATE 'CREATE PUBLIC SYNONYM '||R.TABLE_NAME||' FOR METADADOS.'||R.TABLE_NAME;
	END LOOP;
END;
/

-- GRANTS PUBLIC SYNONYMS [views] (ALTER, CREATE, DROP)
BEGIN
	FOR R IN (SELECT VIEW_NAME FROM DBA_VIEWS WHERE OWNER='METADADOS' AND VIEW_NAME NOT IN (SELECT SYNONYM_NAME FROM DBA_SYNONYMS WHERE OWNER='PUBLIC')) LOOP
		EXECUTE IMMEDIATE 'CREATE PUBLIC SYNONYM '||R.VIEW_NAME||' FOR METADADOS.'||R.VIEW_NAME;
	END LOOP;
END;
/

-- GRANTS PUBLIC SYNONYMS [outros] (ALTER, CREATE, DROP)
BEGIN
	FOR R IN (SELECT OBJECT_NAME FROM DBA_OBJECTS WHERE OWNER='METADADOS' AND OBJECT_TYPE IN ('SEQUENCE','PROCEDURE','PACKAGE','PACKAGE BODY','TRIGGER','FUNCTION','INDEX','TYPE BODY','TYPE') AND OBJECT_NAME NOT IN (SELECT SYNONYM_NAME FROM DBA_SYNONYMS WHERE OWNER='PUBLIC')) LOOP
		EXECUTE IMMEDIATE 'CREATE PUBLIC SYNONYM '||R.OBJECT_NAME||' FOR METADADOS.'||R.OBJECT_NAME;
	END LOOP;
END;
/

-- CHECAGENS
SELECT COUNT(*) FROM dba_tab_privs WHERE GRANTEE='BI';
SELECT COUNT(*) FROM DBA_OBJECTS WHERE OWNER='METADADOS' AND OBJECT_TYPE IN ('TABLE','VIEW','FUNCTION','PROCEDURE','PACKAGE','TRIGGER','SEQUENCE');
SELECT COUNT(*) FROM DBA_OBJECTS WHERE OWNER='METADADOS' AND OBJECT_TYPE IN ('TABLE','VIEW');