SET LINES 300
SET PAGESIZE 100
COL PARAMETER FORMAT A50
COL "SESSION VALUE" FORMAT A20
COL "INSTANCE VALUE" FORMAT  A20
SELECT X.KSPPINM "PARAMETER",
Y.KSPPSTVL "SESSION VALUE",
Z.KSPPSTVL "INSTANCE VALUE"
FROM   X$KSPPI X,
X$KSPPCV Y,
X$KSPPSV Z
WHERE  X.INDX = Y.INDX
AND    X.INDX = Z.INDX
AND    X.KSPPINM LIKE '/_AWR%' ESCAPE '/'
ORDER BY X.KSPPINM;