SELECT OBJECT_TYPE,COUNT(OBJECT_TYPE) FROM SYSTEM.SYS_IMPORT_SCHEMA_01 WHERE OBJECT_TYPE=(SELECT OBJECT_TYPE FROM SYSTEM.SYS_IMPORT_SCHEMA_01 WHERE IN_PROGRESS IS NOT NULL) GROUP BY OBJECT_TYPE;

SELECT OBJECT_TYPE,OBJECT_SCHEMA,OBJECT_NAME FROM SYS.SYS_IMPORT_SCHEMA_01 WHERE IN_PROGRESS IS NOT NULL;