SET LINES 300
SET PAGESIZE 100
COL OWNER FOR A15
COL "JOB" FOR A35
COL JOB_ACTION FOR A120
COL "START DATE" FOR A20
COL "DURATION" FOR A10
SELECT OWNER, JOB_NAME "JOB", JOB_ACTION, TO_CHAR(LAST_START_DATE,'DD/MM/YYYY HH24:MI:SS') "START DATE", REGEXP_SUBSTR(LAST_RUN_DURATION,'\D{2}:\D{2}:\D{2}') "DURATION" FROM DBA_SCHEDULER_JOBS
ORDER BY LAST_START_DATE;


SET LINES 300
SET PAGESIZE 100
COL JOB FOR 99999999
COL "OWNER" FOR A15
COL BROKEN FOR A1
COL "LAST RUN" FOR A20
COL WHAT FOR A100
SELECT JOB, SCHEMA_USER "OWNER", BROKEN, CONCAT(CONCAT(LAST_DATE,' '), LAST_SEC) "LAST RUN", WHAT FROM DBA_JOBS
ORDER BY LAST_DATE,LAST_SEC;