--Here is one script to display all references to a table using a non-correlated subquery:

SELECT * 
FROM DBA_CONSTRAINTS 
WHERE R_CONSTRAINT_NAME IN (SELECT CONSTRAINT_NAME FROM DBA_CONSTRAINTS WHERE TABLE_NAME='TOTVS10.SRECMP');
	   
	   
--This SQL will show all dependent tables for a table, all reference to the table within other tables:   
	   
SELECT CONS.OWNER AS CHILD_OWNER, CONS.TABLE_NAME AS CHILD_TABLE, CONS.CONSTRAINT_NAME CONSTAINT_NAME, CONS.CONSTRAINT_TYPE CONSTRAINT_TYPE, COL.OWNER PARENT_OWNER, COL.TABLE_NAME PARENT_TABLE, COL.COLUMN_NAME COLUMN_NAME
FROM DBA_CONS_COLUMNS COL, DBA_CONSTRAINTS CONS
WHERE CONS.R_OWNER = COL.OWNER
AND CONS.R_CONSTRAINT_NAME = COL.CONSTRAINT_NAME
AND CONS.TABLE_NAME = 'TOTVS10.SRECMP';