SET PAUSE ON
SET PAUSE 'PRESS RETURN TO CONTINUE'
SET PAGESIZE 60
SET LINESIZE 300
SELECT
   CHR(10)||
   'CHECK FOR SESSION ID ---->  '||LPAD( S.SID, 4 )||CHR(10)||CHR(10) AS "SESSION ID"
FROM
   V$SESSION S, V$PROCESS P
WHERE
   P.ADDR = S.PADDR AND
   P.SPID = &ENTER_OSPID
/