SET LINES 300
SET PAGESIZE 100
SET VERIFY OFF
COLUMN FILE_NAME FORMAT A50 WORD_WRAPPED
COLUMN SMALLEST FORMAT 999,990 HEADING "SMALLEST_SIZE"
COLUMN CURRSIZE FORMAT 999,990 HEADING "CURR_SIZE"
COLUMN SAVINGS FORMAT 999,990 HEADING "POSS_SAVINGS"
BREAK ON REPORT
COMPUTE SUM OF SAVINGS ON REPORT
COLUMN VALUE NEW_VAL BLKSIZE
-- GET BLOCK SIZE
SELECT 
	VALUE 
FROM 
	V$PARAMETER 
WHERE 
	NAME='db_block_size'
/
-- GET DATAFILE SIZES
SELECT 
	FILE_NAME, 
	CEIL((NVL(HWM,1)*&&BLKSIZE)/1024/1024) SMALLEST, 
	CEIL(BLOCKS*&&BLKSIZE/1024/1024) CURRSIZE, 
	CEIL(BLOCKS*&&BLKSIZE/1024/1024)-CEIL((NVL(HWM,1)*&&BLKSIZE)/1024/1024) SAVINGS
FROM 
	DBA_DATA_FILES A,
	(
		SELECT 
			FILE_ID, 
			MAX(BLOCK_ID+BLOCKS-1) HWM 
		FROM 
			DBA_EXTENTS 
		GROUP BY 
			FILE_ID
	) B
WHERE 
	A.FILE_ID=B.FILE_ID(+)
/
-- GENERATE ALTER DATAFILE COMMANDS
COLUMN CMD FORMAT A75 WORD_WRAPPED
SELECT 
	'ALTER DATABASE DATAFILE '''||FILE_NAME||''' RESIZE ' ||CEIL( (NVL(HWM,1)*&&BLKSIZE)/1024/1024) || 'M;' CMD
FROM 
	DBA_DATA_FILES A,
	(
		SELECT 
			FILE_ID, 
			MAX(BLOCK_ID+BLOCKS-1) HWM 
		FROM 
			DBA_EXTENTS 
		GROUP BY 
			FILE_ID
	) B
WHERE 
	A.FILE_ID=B.FILE_ID(+)
	AND CEIL(BLOCKS*&&BLKSIZE/1024/1024)-CEIL((NVL(HWM,1)*&&BLKSIZE)/1024/1024)>0
/