#set -x
#!/bin/sh

sqlplus / as sysdba <<EOF
SET PAGESIZE 0
SET LINESIZE 2000
SET FEED OFF
SET TERMOUT OFF
SET TERM OFF
SET TRIMS ON
SET VERIFY OFF
SET TIMING OFF
COL DS_URL_SERVIDOR FOR A50
COL DS_URL_SERV_RELATORIO FOR A50

SPOOL /u03/app/oracle/backup/datapump/restore_produtosistema.sql

SELECT 'UPDATE DBASGU.PRODUTO_SISTEMA SET DS_URL_SERVIDOR=''' || DS_URL_SERVIDOR || ''', DS_URL_SERV_RELATORIO=''' || DS_URL_SERV_RELATORIO || ''' WHERE CD_PRODUTO=''' || CD_PRODUTO || ''';'  COMMAND FROM  DBASGU.PRODUTO_SISTEMA;

SELECT 'COMMIT;' COMMAND FROM DUAL;

SET HEADING ON
SET FEEDBACK ON
SET VERIFY ON
SPOOL OFF
EXIT;
EOF

#set -x
#!/bin/sh

sqlplus / as sysdba <<EOF
SET PAGESIZE 0
SET LINESIZE 2000
SET FEED OFF
SET TERMOUT OFF
SET TERM OFF
SET TRIMS ON
SET VERIFY OFF
SET TIMING OFF
COL VALOR FOR A80

SPOOL /u03/app/oracle/backup/datapump/restore_configuracao_valor_report.sql

SELECT 'UPDATE DBAMV.CONFIGURACAO SET VALOR=''' || VALOR || ''' WHERE CD_SISTEMA = ''GLOBAL'' AND CHAVE = ''URL_NOVO_REPORT_SOUL'';' COMMAND FROM DBAMV.CONFIGURACAO WHERE CD_SISTEMA = 'GLOBAL' AND CHAVE = 'URL_NOVO_REPORT_SOUL';

SELECT 'COMMIT;' COMMAND FROM DUAL;

SET HEADING ON
SET FEEDBACK ON
SET VERIFY ON
SPOOL OFF
EXIT;
EOF