COL HWM_OPEN_CUR FORMAT 99,999
COL MAX_OPEN_CUR FORMAT 99,999
SELECT MAX(A.VALUE) AS HWM_OPEN_CUR, P.VALUE AS MAX_OPEN_CUR
FROM V$SESSTAT A, V$STATNAME B, V$PARAMETER P
WHERE A.STATISTIC# = B.STATISTIC# 
AND B.NAME = 'OPENED CURSORS CURRENT'
AND P.NAME= 'OPEN_CURSORS'
GROUP BY P.VALUE;