SET LINES 300
SET PAGESIZE 1000
SET LONG 1000
COL "PL_SQL_OBJ" FOR A50
COL EVENT FOR A40
COL USERNAME FOR A10
COL SQL_TEXT FOR A45
SELECT 
	TT.*,S.SQL_TEXT 
FROM
	(SELECT 
		T.TIME#,
		SUM(T.PCT_TIME) "PCT_DB_TIME",
		T.TOT_ACT_SESS,
		T.PL_SQL_OBJ,
		T.SQL_ID,
		T.EVENT,
		T.USERNAME 
	FROM 
		(SELECT 
			TO_CHAR(TRUNC(ASH.SAMPLE_TIME,'MI')-MOD(EXTRACT(MINUTE FROM ASH.SAMPLE_TIME),&&SAMPLE_INTERVAL_IN_MINUTES)/(24*60),'DD/MM/YY') "TIME#",
			100*ROUND(SUM(ASH.TM_DELTA_DB_TIME)/(SUM(SUM(ASH.TM_DELTA_DB_TIME)) OVER(PARTITION BY TRUNC(SAMPLE_TIME,'MI')-MOD(EXTRACT(MINUTE FROM ASH.SAMPLE_TIME),&&SAMPLE_INTERVAL_IN_MINUTES)/(24*60))),2) "PCT_TIME",
			COUNT(DISTINCT ASH.SESSION_ID) OVER(PARTITION BY TRUNC(ASH.SAMPLE_TIME,'MI')-MOD(EXTRACT(MINUTE FROM ASH.SAMPLE_TIME),&&SAMPLE_INTERVAL_IN_MINUTES)/(24*60)) "TOT_ACT_SESS",
			ASH.SESSION_ID, 
			ASH.SESSION_SERIAL#,
			DP.OWNER||NVL2(DP.OBJECT_NAME,'.'||DP.OBJECT_NAME,NULL) ||NVL2(DP.PROCEDURE_NAME,'.'||DP.PROCEDURE_NAME,NULL) "PL_SQL_OBJ",           
			ASH.SQL_ID,
			ASH.EVENT,
			DU.USERNAME
		FROM 
			DBA_HIST_ACTIVE_SESS_HISTORY ASH
		LEFT JOIN DBA_PROCEDURES DP ON DP.OBJECT_ID=ASH.PLSQL_ENTRY_OBJECT_ID AND DP.SUBPROGRAM_ID=ASH.PLSQL_ENTRY_SUBPROGRAM_ID
		JOIN DBA_USERS DU ON DU.USER_ID=ASH.USER_ID
		WHERE 
			ASH.SAMPLE_TIME BETWEEN TRUNC (SYSDATE -2) +14/24 +30/(24*60) 
			AND TRUNC(SYSDATE-2)+16/24+30/(24*60)
		GROUP BY DP.OWNER||NVL2(DP.OBJECT_NAME,'.'||DP.OBJECT_NAME,NULL) ||NVL2(DP.PROCEDURE_NAME,'.'||DP.PROCEDURE_NAME,NULL),SQL_ID ,ASH.EVENT,
		TRUNC(SAMPLE_TIME,'MI')-MOD(EXTRACT(MINUTE FROM SAMPLE_TIME),&&SAMPLE_INTERVAL_IN_MINUTES)/(24*60) ,
		SESSION_ID,SESSION_SERIAL#,DU.USERNAME) T
	GROUP BY T.TIME#,T.TOT_ACT_SESS,T.PL_SQL_OBJ,T.SQL_ID,T.USERNAME,T.EVENT) TT
LEFT JOIN DBA_HIST_SQLTEXT S ON TT.SQL_ID=S.SQL_ID
WHERE 
	TT.PCT_DB_TIME >0
ORDER BY 1 ASC,2 DESC;