
-- check not valid indexes
SELECT OWNER, INDEX_NAME, INDEX_TYPE, TABLE_OWNER, COMPRESSION, STATUS FROM DBA_INDEXES WHERE TABLE_OWNER = 'PRODUCTS' AND STATUS <> 'VALID';

-- Check unusable index partitions
SELECT INDEX_OWNER,INDEX_NAME,PARTITION_NAME,SUBPARTITION_COUNT,TABLESPACE_NAME,STATUS FROM DBA_IND_PARTITIONS WHERE INDEX_OWNER='PRODUCTS' AND STATUS='UNUSABLE';


-- List the commands to rebuild
SET SERVEROUTPUT ON;
DECLARE
  v_sql VARCHAR2(1000);
BEGIN
  FOR idx IN (
    SELECT INDEX_OWNER, INDEX_NAME, PARTITION_NAME, TABLESPACE_NAME
    FROM DBA_IND_PARTITIONS
    WHERE INDEX_OWNER = '&&INDEX_OWNER'
    AND TABLESPACE_NAME = '&&TABLESPACE_NAME'
	AND STATUS='UNUSABLE'
  )
  LOOP
    v_sql := 'ALTER INDEX ' || idx.index_owner || '.' || idx.index_name || ' REBUILD PARTITION ' || idx.partition_name || ' TABLESPACE ' || idx.tablespace_name || ';';
    DBMS_OUTPUT.PUT_LINE(v_sql);
  END LOOP;
END;
/



ALTER INDEX PRODUCTS.IDX_CAINLOGS_SRCDESC REBUILD PARTITION PART_20231224 TABLESPACE PRODUCTS_INDX;