

SELECT TABLESPACE_NAME, FILE_NAME FROM DBA_TEMP_FILES;

CREATE TEMPORARY TABLESPACE TEMP1 TEMPFILE  '/u01/app/oradata/DBACLASS/temp101.dbf' SIZE 2G;

ALTER DATABASE DEFAULT TEMPORARY TABLESPACE TEMP1;

SELECT B.TABLESPACE, B.SEGFILE#, B.SEGBLK#, B.BLOCKS, A.SID, A.SERIAL, A.USERNAME, A.OSUSER, A.STATUS
FROM V$SESSION A, V$SORT_USAGE B
WHERE A.SADDR = B.SESSION_ADDR;

DROP TABLESPACE TEMP INCLUDING CONTENTS AND DATAFILES;

CREATE TEMPORARY TABLESPACE TEMP TEMPFILE  '/u01/app/oradata/DBACLASS/temp01.dbf' SIZE 2G AUTOEXTEND ON NEXT 256M MAXSIZE 16G;

ALTER DATABASE DEFAULT TEMPORARY TABLESPACE TEMP;

DROP TABLESPACE TEMP1 INCLUDING CONTENTS AND DATAFILES;