--Standby:
SET LINES 300
SELECT * FROM V$RECOVER_FILE WHERE ERROR LIKE '%FILE%';

--Produção:
SET LINES 300
SELECT FILE#,NAME FROM V$DATAFILE WHERE FILE#=12;

--Standby:
SET LINES 300
SELECT FILE#,NAME FROM V$DATAFILE WHERE FILE#=12;

ALTER SYSTEM SET STANDBY_FILE_MANAGEMENT='MANUAL';

ALTER DATABASE CREATE DATAFILE '/u01/app/oracle/product/11.2.0/db_1/dbs/UNNAMED00012' AS '/u01/app/oracle/oradata/ipe/standby/tsi_sistema_abcp01.dbf';

ALTER SYSTEM SET STANDBY_FILE_MANAGEMENT='AUTO';

ALTER DATABASE RECOVER MANAGED STANDBY DATABASE DISCONNECT FROM SESSION;