SET LINES 300
SET PAGESIZE 100
COL TARGET FOR A10
COL MESSAGE FOR A70
COL USERNAME FOR A10
COL OPNAME FOR A30
COL UNITS FOR A6
COL SID FOR 99999
COL TIME_REMAINING FOR 9999999
SELECT TO_CHAR(SYSDATE,'DD-MON HH24:MI:SS') COLLECTION_DATESTAMP, SID, OPNAME, TARGET, SOFAR, TOTALWORK, UNITS, TO_CHAR(START_TIME,'HH24:MI:SS') STARTTIME, TIME_REMAINING AS TIME_REM, MESSAGE, USERNAME
FROM V$SESSION_LONGOPS
WHERE SOFAR != TOTALWORK
ORDER BY START_TIME;