SET LINES 200 PAGESIZE 80
COL HASH_VALUE FORMAT A50
COL TABLESPACE FORMAT A15
COL USERNAME FORMAT A20
SELECT S.INST_ID, S.SID, S.USERNAME, U.TABLESPACE, S.SQL_ID,U.SQLHASH, U.SEGTYPE, U.CONTENTS, U.BLOCKS
FROM GV$SESSION S, GV$TEMPSEG_USAGE U
WHERE S.SADDR=U.SESSION_ADDR
AND U.BLOCKS > 128
ORDER BY U.BLOCKS;