COL TYPE FOR A20 HEADING "BACKUP TYPE"
COL COMPLETION_TIME HEADING "COMPLETION TIME"
COL MB FOR 99999999999  HEADING "SIZE (MB)"
COL BCPTIME FOR 99999999999 HEADING "BACKUP TIME (MINUTES)"
SELECT TO_CHAR (COMPLETION_TIME, 'YYYY-MON-DD') COMPLETION_TIME
       , TYPE
       , ROUND (SUM (BYTES) / 1048576)          MB
       , ROUND (SUM (ELAPSED_SECONDS) / 60)     BCPTIME
    FROM (SELECT CASE
                    WHEN S.BACKUP_TYPE = 'L' THEN 'ARCHIVE LOG'
--                    WHEN S.CONTROLFILE_INCLUDED = 'YES' THEN 'CONTROL FILE'
                 WHEN S.BACKUP_TYPE = 'D' THEN 'FULL (LEVEL ' || NVL (S.INCREMENTAL_LEVEL, 0) || ')'
                    WHEN S.BACKUP_TYPE = 'I' THEN 'INCEMENTAL (LEVEL ' || S.INCREMENTAL_LEVEL || ')'
                    ELSE S.BACKUP_TYPE
                 END
                    TYPE
               , TRUNC (S.COMPLETION_TIME) COMPLETION_TIME
               , P.TAG
               , P.BYTES
               , S.ELAPSED_SECONDS
            FROM V$BACKUP_PIECE P, V$BACKUP_SET S
           WHERE STATUS = 'A' AND P.RECID = S.RECID
          UNION ALL
          SELECT 'DATAFILE COPY' TYPE, TRUNC (COMPLETION_TIME), TAG, OUTPUT_BYTES, 0 ELAPSED_SECONDS FROM V$BACKUP_COPY_DETAILS)
GROUP BY TAG, TO_CHAR (COMPLETION_TIME, 'YYYY-MON-DD'), TYPE
ORDER BY 1 ASC, 2, 3;