--FIND QUERY DETAILS BY SQL_ID:
SET LINES 300
SET PAGESIZE 1000
SELECT A.INSTANCE_NUMBER INST_ID, A.SNAP_ID,A.PLAN_HASH_VALUE "PLAN HASH", TO_CHAR(BEGIN_INTERVAL_TIME,'DD-MON-YY HH24:MI') "BTIME", ABS(EXTRACT(MINUTE FROM (END_INTERVAL_TIME-BEGIN_INTERVAL_TIME)) + EXTRACT(HOUR FROM (END_INTERVAL_TIME-BEGIN_INTERVAL_TIME))*60 + EXTRACT(DAY FROM (END_INTERVAL_TIME-BEGIN_INTERVAL_TIME))*24*60) "MINUTES",
EXECUTIONS_DELTA "EXECS", ROUND(ELAPSED_TIME_DELTA/1000000/GREATEST(EXECUTIONS_DELTA,1),4) "AVG DUR (SEC)" 
FROM DBA_HIST_SQLSTAT A, DBA_HIST_SNAPSHOT B
WHERE SQL_ID='625xmt1bxatjs' AND A.SNAP_ID=B.SNAP_ID
AND A.INSTANCE_NUMBER=B.INSTANCE_NUMBER
ORDER BY SNAP_ID DESC, A.INSTANCE_NUMBER;

-- FIND SESSIONS BY SQL_ID:
SELECT UNIQUE USER_ID FROM V$ACTIVE_SESSION_HISTORY WHERE SQL_ID = '&SQL_ID';
SELECT USER_ID FROM DBA_HIST_ACTIVE_SESS_HISTORY WHERE SQL_ID = '6pgpwqfm57upm';

SELECT USER_ID,USERNAME FROM DBA_USERS WHERE USER_ID = '132';

SELECT USER_ID,USERNAME FROM DBA_USERS WHERE USER_ID = (SELECT UNIQUE USER_ID FROM V$ACTIVE_SESSION_HISTORY WHERE SQL_ID = '6pgpwqfm57upm');

-- FIND SID/SERIAL BY SQL_ID:
SELECT S.SID,S.SERIAL#,S.USERNAME,S.SQL_ID,Q.SQL_TEXT
FROM V$SQLAREA Q ,GV$SESSION S
WHERE S.SQL_HASH_VALUE = Q.HASH_VALUE
AND S.SQL_ADDRESS = Q.ADDRESS
AND S.USERNAME IS NOT NULL
AND S.SQL_ID='6pgpwqfm57upm';

--FIND SQL BY PID (01):
PROMPT "PLEASE ENTER THE UNIX PROCESS ID"
SET PAGESIZE 50000
SET LINESIZE 30000
SET LONG 500000
SET HEAD OFF
SELECT S.USERNAME SU, SUBSTR(SA.SQL_TEXT,1,540) TXT
FROM V$PROCESS P, V$SESSION S, V$SQLAREA SA
WHERE P.ADDR=S.PADDR AND S.USERNAME IS NOT NULL AND S.SQL_ADDRESS=SA.ADDRESS(+) AND S.SQL_HASH_VALUE=SA.HASH_VALUE(+) AND SPID=&SPID;

--FIND SQL BY PID (02):
SELECT SQL_TEXT
FROM V$SQL
WHERE SQL_ID = (SELECT SQL_ID FROM V$SESSION WHERE PADDR = (SELECT ADDR FROM V$PROCESS WHERE SPID = '&PROCESS_ID'));


-- FIND PID BY SQLID:
SET LINES 300
SET PAGESIZE 100
SET LONG 100
SELECT A.SID, A.SERIAL#,A.USERNAME, A.OSUSER, B.SPID FROM V$SESSION A, V$PROCESS B WHERE A.PADDR= B.ADDR
AND A.SID IN (SELECT SID FROM V$SESSION WHERE SQL_ID='&&SQL_ID') ORDER BY A.SID;