SET LINES 300
COL TABLE_NAME FOR A30
COL COLUMN_NAME FOR A30
COL CONSTRAINT_NAME FOR A30
COL OWNER FOR A10
COL R_OWNER FOR A10
COL R_TABLE_NAME FOR A20
COL R_PK FOR A20
SELECT A.TABLE_NAME, A.COLUMN_NAME, A.CONSTRAINT_NAME, C.OWNER, C.R_OWNER, C_PK.TABLE_NAME R_TABLE_NAME, C_PK.CONSTRAINT_NAME R_PK
FROM ALL_CONS_COLUMNS A
JOIN ALL_CONSTRAINTS C ON A.OWNER = C.OWNER AND A.CONSTRAINT_NAME = C.CONSTRAINT_NAME
JOIN ALL_CONSTRAINTS C_PK ON C.R_OWNER = C_PK.OWNER AND C.R_CONSTRAINT_NAME = C_PK.CONSTRAINT_NAME
WHERE C.CONSTRAINT_TYPE = 'R'
AND A.OWNER = 'TASY'
AND A.TABLE_NAME = 'VALOR_DOMINIO';



SELECT * FROM DBA_CONSTRAINTS WHERE (R_OWNER, R_CONSTRAINT_NAME) IN (SELECT OWNER,CONSTRAINT_TYPE FROM DBA_CONSTRAINTS WHERE OWNER = 'TASY' AND TABLE_NAME = 'VALOR_DOMINIO' AND CONSTRAINT_TYPE = 'P');