

--https://docs.cloud.oracle.com/iaas/Content/Database/References/timezones.htm

-- validar geraçãode archives:
ALTER SESSION SET NLS_DATE_FORMAT='DD/MM/YYYY HH24:MI:SS';

ALTER SYSTEM SWITCH LOGFILE;

SET LINES 300 PAGESIZE 100
SELECT * FROM (SELECT FIRST_TIME, SEQUENCE# FROM V$ARCHIVED_LOG ORDER BY SEQUENCE# DESC) WHERE ROWNUM <=20 ORDER BY ROWNUM DESC;

SELECT SYSDATE FROM DUAL;