SELECT 
	T.* 
FROM 
	(SELECT 
		OWNER,
		OBJECT_NAME,
		ROUND(100*(SUM(DECODE(STATISTIC_NAME,'LOGICAL READS',VALUE,NULL))/SUM(SUM(VALUE)) OVER(PARTITION BY OWNER,OBJECT_NAME)),3) "L_READS",
		ROUND(100*(SUM(DECODE(STATISTIC_NAME,'PHYSICAL READS',VALUE,NULL))/SUM(SUM(VALUE)) OVER(PARTITION BY OWNER,OBJECT_NAME)),3) "P_READS",
		ROUND(100*(SUM(DECODE(STATISTIC_NAME,'PHYSICAL READS DIRECT',VALUE,NULL))/SUM(SUM(VALUE)) OVER(PARTITION BY OWNER,OBJECT_NAME)),3) "P_READS_D",
		ROUND(100*(SUM(DECODE(STATISTIC_NAME,'PHYSICAL WRITES',VALUE,'PHYSICAL WRITES DIRECT',VALUE,NULL))/SUM(SUM(VALUE)) OVER(PARTITION BY OWNER,OBJECT_NAME)),3) "P_WRITES_D",
		ROUND(100*SUM(VALUE)/SUM(SUM(VALUE)) OVER(),2) "TOTAL"
	FROM 
		V$SEGMENT_STATISTICS
	WHERE
		OBJECT_TYPE IN ('TABLE', 'INDEX')
		AND OWNER='&OWNER'
		AND STATISTIC_NAME IN ('LOGICAL READS','PHYSICAL READS','PHYSICAL READS DIRECT','PHYSICAL WRITES','PHYSICAL WRITES DIRECT')
	GROUP BY OBJECT_NAME,OWNER
	ORDER BY SUM(VALUE) DESC) T 
WHERE 
	ROWNUM < 21;