SELECT 
	ROUND(100*(SUM (TIME_WAITED))/SUM (SUM (TIME_WAITED)) OVER( ),1) "TOTAL_PCT",
	OBJECT_NAME,MIN(SAMPLE_TIME) "START_TIME",
	MAX(SAMPLE_TIME) "END_TIME"
FROM 
	DBA_OBJECTS O, GV$ACTIVE_SESSION_HISTORY ASH
WHERE 
	ASH.SAMPLE_TIME > SYSDATE - 10/(24*60)
	AND O.OBJECT_ID = ASH.CURRENT_OBJ#
	AND ASH.WAIT_CLASS='USER I/O'
	AND ASH.TIME_WAITED IS NOT NULL
GROUP BY OBJECT_NAME 
ORDER BY 1 DESC;