--DESABILITAR:
SHOW PARAMETER JOB_QUEUE_PROCESSES

ALTER SYSTEM SET JOB_QUEUE_PROCESSES=0 SCOPE=BOTH;

UPDATE TASY.APLICACAO_TASY SET IE_STATUS_APLICACAO = 'U';
COMMIT;

--HABILITAR:
ALTER SYSTEM SET JOB_QUEUE_PROCESSES=1000 SCOPE=BOTH;

UPDATE TASY.APLICACAO_TASY SET IE_STATUS_APLICACAO = 'A';
COMMIT;


SELECT IE_STATUS_APLICACAO FROM TASY.APLICACAO_TASY;

SET PAGES 300
SET LINES 300
COL LEV1 FOR A10
COL MIN_IN_WAIT FOR 99999
COL USERNAME FOR A10
COL EVENT FOR A30
COL PROGRAMA FOR A10
COL BLOCKING_SESSION FOR 9999999
SELECT LEV1,MIN_IN_WAIT AS "W(MIN)",USERNAME,OSUSER,SQL_ID,PROGRAMA,BLOCKING_SESSION AS "BLOCKING",EVENT,SID || ',' || SERIAL# AS "SESSION",ACAO,MODULO FROM PROCESSO_LOCK_V_NEW;


SET PAGES 300
SET LINES 300
COL LEV1 FOR A10
COL MIN_IN_WAIT FOR 99999
COL USERNAME FOR A10
COL EVENT FOR A30
COL PROGRAMA FOR A10
COL BLOCKING_SESSION FOR 9999999
SELECT LEV1,MIN_IN_WAIT AS "W(MIN)",USERNAME,OSUSER,SQL_ID,PROGRAMA,BLOCKING_SESSION AS "BLOCKING",EVENT,SID || ',' || SERIAL# AS "SESSION",ACAO,MODULO FROM PROCESSO_LOCK_V_NEW WHERE SID = 420;

/*
======================================================================

SHO PARAMETER QUEUE

NAME                                 TYPE        VALUE
------------------------------------ ----------- ------------------------------
JOB_QUEUE_PROCESSES                  INTEGER     1000
UNIFIED_AUDIT_SGA_QUEUE_SIZE         INTEGER     1048576

*/
