/*SET LINESIZE 300
SET PAGESIZE 100
col DATA format a10;
col TABLESPACE_NAME format a30;
SELECT  TO_CHAR(SYSDATE,'dd/mm/yyyy') DATA,A.TABLESPACE_NAME,
        ROUND((A.BYTES)/1024/1024,2) TOTAL_SIZE,
        ROUND((A.BYTES-B.BYTES)/1024/1024,2) UTILIZADO_SIZE,
        ROUND((B.BYTES)/1024/1024,2) LIVRE_SIZE,
        ROUND(((A.BYTES-B.BYTES)/A.BYTES)*100,2) PERCENT_UTILIZADO
FROM
        (       SELECT  TABLESPACE_NAME,
                        SUM(BYTES) BYTES
                FROM    DBA_DATA_FILES
                GROUP BY TABLESPACE_NAME) A,
        (       
                SELECT  TABLESPACE_NAME,
                        SUM(BYTES) BYTES
                FROM    DBA_FREE_SPACE
                GROUP BY TABLESPACE_NAME) B
WHERE  A.TABLESPACE_NAME=B.TABLESPACE_NAME
UNION ALL
SELECT  TO_CHAR(SYSDATE,'dd/mm/yyyy'),A.TABLESPACE_NAME,
        ROUND((A.BYTES)/1024/1024,2) TOTAL_SIZE,
        ROUND((A.BYTES-B.BYTES)/1024/1024,2) UTILIZADO_SIZE,
        ROUND((B.BYTES)/1024/1024,2) LIVRE_SIZE,
        ROUND(((A.BYTES-B.BYTES)/A.BYTES)*100,2) PERCENT_UTILIZADO
FROM
        (       SELECT  TABLESPACE_NAME,
                        SUM(BYTES) BYTES
                FROM    DBA_TEMP_FILES
                GROUP BY TABLESPACE_NAME) A,
        (       
                SELECT  TABLESPACE_NAME,
                        SUM(BYTES_FREE) BYTES
                FROM    V$TEMP_SPACE_HEADER
                GROUP BY TABLESPACE_NAME) B 
WHERE  A.TABLESPACE_NAME=B.TABLESPACE_NAME
ORDER  BY 2 ASC;*/


-----COM AUTOEXTEND

-- PARA O PERCENT USADO DO MAX FAZER O MENOR / PELO MAIOR * 100

SET LINESIZE 300
SET PAGESIZE 100
col DATA format a10;
col TABLESPACE_NAME format a30;
SELECT  TO_CHAR(SYSDATE,'dd/mm/yyyy') DATA,A.TABLESPACE_NAME,
        ROUND((A.BYTES)/1024/1024,2) TOTAL_SIZE,
		ROUND((A.MAXBYTES)/1024/1024,2) TOTAL_MAX_SIZE,
        ROUND((A.BYTES-B.BYTES)/1024/1024,2) UTILIZADO_SIZE,
        ROUND((B.BYTES)/1024/1024,2) LIVRE_SIZE,
        ROUND(((A.BYTES-B.BYTES)/A.BYTES)*100,2) PERCENT_UTILIZADO
		,ROUND(((A.BYTES-B.BYTES)/A.MAXBYTES)*100,2) PERCENT_FROM_MAX
FROM
        (       SELECT  TABLESPACE_NAME,
                        SUM(BYTES) BYTES,
						--sum(decode(AUTOEXTENSIBLE, 'YES', MAXBYTES, BYTES)) MAXBYTES
						SUM(CASE WHEN (AUTOEXTENSIBLE='YES' AND MAXBYTES>BYTES) THEN MAXBYTES ELSE BYTES END) MAXBYTES
                FROM    DBA_DATA_FILES
                GROUP BY TABLESPACE_NAME) A,
        (       
                SELECT  TABLESPACE_NAME,
                        SUM(BYTES) BYTES,
						'' VAZIO
                FROM    DBA_FREE_SPACE
                GROUP BY TABLESPACE_NAME) B
WHERE  A.TABLESPACE_NAME=B.TABLESPACE_NAME
UNION ALL
SELECT  TO_CHAR(SYSDATE,'dd/mm/yyyy'),A.TABLESPACE_NAME,
        ROUND((A.BYTES)/1024/1024,2) TOTAL_SIZE,
		ROUND((A.MAXBYTES)/1024/1024,2) TOTAL_MAX_SIZE,
        ROUND((A.BYTES-B.BYTES)/1024/1024,2) UTILIZADO_SIZE,
        ROUND((B.BYTES)/1024/1024,2) LIVRE_SIZE,
        ROUND(((A.BYTES-B.BYTES)/A.BYTES)*100,2) PERCENT_UTILIZADO
		,ROUND(((A.BYTES-B.BYTES)/A.MAXBYTES)*100,2)
FROM
        (       SELECT  TABLESPACE_NAME,
                        SUM(BYTES) BYTES,
						SUM(CASE WHEN (AUTOEXTENSIBLE='YES' AND MAXBYTES>BYTES) THEN MAXBYTES ELSE BYTES END) MAXBYTES
                FROM    DBA_TEMP_FILES
                GROUP BY TABLESPACE_NAME) A,
        (
                SELECT  TABLESPACE_NAME,
                        SUM(BYTES_FREE) BYTES
                FROM    V$TEMP_SPACE_HEADER
                GROUP BY TABLESPACE_NAME) B 
WHERE  A.TABLESPACE_NAME=B.TABLESPACE_NAME
ORDER  BY 2 ASC;


