SELECT 'GRANT ' || DECODE(OBJECT_TYPE, 'PACKAGE', 'DEBUG','PACKAGE BODY', 'DEBUG', 'FUNCTION', 'DEBUG', 'PROCEDURE', 'DEBUG') ||
' ON ' || 'DBAASS.'||OBJECT_NAME || ' TO R_DEBUG_DEV;'
FROM DBA_OBJECTS
WHERE OWNER = 'DBAASS' AND OBJECT_TYPE IN ('PACKAGE','PACKAGE BODY','FUNCTION','PROCEDURE');




SELECT 'GRANT ' || DECODE(OBJECT_TYPE, 'PACKAGE', 'EXECUTE','PACKAGE BODY', 'EXECUTE', 'FUNCTION', 'EXECUTE', 'PROCEDURE', 'EXECUTE') ||
' ON ' || 'DBAASS.'||OBJECT_NAME || ' TO R_EXECUTE_DEV;'
FROM DBA_OBJECTS
WHERE OWNER = 'DBAASS' AND OBJECT_TYPE IN ('PACKAGE','PACKAGE BODY', 'FUNCTION', 'EXECUTE');



==========================================================================================================================



select * from dba_tab_privs where grantee='U_alexander.probst' and owner='DBAASS' AND TABLE_NAME like 'TRB_%';


SELECT 'GRANT ' || DECODE(OBJECT_TYPE, 'TRIGGER', 'DEBUG') ||
' ON ' || 'DBAASS.'||OBJECT_NAME || ' TO R_DEBUG_DEV;'
FROM DBA_OBJECTS
WHERE OWNER = 'DBAASS' AND OBJECT_TYPE IN ('TRIGGER');




	SELECT 'GRANT ' || DECODE(OBJECT_TYPE, 'TRIGGER', 'EXECUTE') ||
	' ON ' || 'DBAASS.'||OBJECT_NAME || ' TO R_EXECUTE_DEV;'
	FROM DBA_OBJECTS
	WHERE OWNER = 'DBAASS' AND OBJECT_TYPE IN ('TRIGGER');