#set -x
#!/bin/sh

## VARIAVEIS AMBIENTE
. /etc/ambiente_terra.sh

## VARIAVEIS SCRIPT
export GZ_FILE=ls -t terra.TOTVS01*.gz | head -n1
export DP_BKP=/backup/datapump/files/

## VARIAVEIS IMPORT
export DP_DIR=DATA_PUMP
export DP_FILE=${GZ_FILE::-3}
export DP_LOG=imp_totvs_teste_`date +%Y%m%d%H%M`.log
export DP_OWNER=TOTVS
export DP_OWNER_2=TOTVS_TESTE
export DP_DATA=DATA
export DP_DATA_2=DATA_TESTE
export DP_INDEX=INDEXES
export DP_INDEX_2=INDEXES_TESTE

## CRIA ARQUIVO DE DROP
sqlplus / as sysdba <<EOF
SET HEADING OFF
SET FEEDBACK OFF
SET OFF PAGESIZE 0
SET VERIFY OFF
SET PAGESIZE 200
SET LINES 300
SPOOL /home/oracle/LIMPA_SCHEMA_${DP_OWNER_2}.sql
SELECT 'ALTER TABLE '||OWNER||'."'||TABLE_NAME||'" DROP CONSTRAINT "'||CONSTRAINT_NAME||'";' FROM DBA_CONSTRAINTS WHERE OWNER IN ('${DP_OWNER_2}') AND CONSTRAINT_TYPE = 'R'
/
 SELECT DISTINCT 'DROP SEQUENCE '||SEQUENCE_OWNER||'."'||SEQUENCE_NAME||'";' FROM DBA_SEQUENCES WHERE SEQUENCE_OWNER IN ('${DP_OWNER_2}')
/
 SELECT DISTINCT 'DROP '||TYPE||' '||OWNER||'."'||NAME||'";' FROM DBA_SOURCE WHERE OWNER IN ('${DP_OWNER_2}')
/
 SELECT 'DROP VIEW '||OWNER||'."'|| VIEW_NAME||'";' FROM DBA_VIEWS WHERE OWNER IN ('${DP_OWNER_2}')
/
 SELECT 'DROP TABLE '||OWNER||'."'||TABLE_NAME||'" PURGE;' FROM DBA_TABLES WHERE OWNER IN ('${DP_OWNER_2}')
/
 SELECT 'DROP SYNONYM '||OWNER||'."'||SYNONYM_NAME||'";' FROM DBA_SYNONYMS WHERE OWNER IN ('${DP_OWNER_2}')
/
 SELECT 'DROP TYPE '||OWNER||'."'||TYPE_NAME||'";' FROM DBA_TYPES WHERE OWNER IN ('${DP_OWNER_2}')
/
 SELECT 'DROP MATERIALIZED VIEW '||OWNER||'."'||MVIEW_NAME||'";' FROM DBA_MVIEWS WHERE OWNER IN ('${DP_OWNER_2}')
/
 SELECT 'DROP PUBLIC SYNONYM ' || SYNONYM_NAME || ';' FROM DBA_SYNONYMS WHERE TABLE_OWNER IN ('${DP_OWNER_2}') AND OWNER = 'PUBLIC' AND DB_LINK IS NULL ORDER BY SYNONYM_NAME
/
SET HEADING ON
SET FEEDBACK ON
SET VERIFY ON
SPOOL OFF
EXIT;
EOF

## EXECUTA DROP DO OWNER
sqlplus / as sysdba <<EOF
@/home/oracle/LIMPA_SCHEMA_${DP_OWNER_2}.sql
DROP USER ${DP_OWNER_2};
EXIT;
EOF

## DESCOMPACTA ARQUIVO
cd ${DP_BKP}
gunzip < ${GZ_FILE} > ${DP_FILE}

## IMPORTA DADOS
IMPDP \'/ as sysdba\' SCHEMAS=${DP_OWNER} REMAP_SCHEMA=${DP_OWNER}:${DP_OWNER_2} REMAP_TABLESPACE=${DP_DATA}:${DP_DATA_2},${DP_INDEX}:${DP_INDEX_2} DIRECTORY=${DP_DIR} DUMPFILE=${DP_FILE} LOGFILE=${DP_LOG} EXCLUDE=STATISTICS

## EFETUA UPDATE
sqlplus / as sysdba <<EOF
UPDATE ${DP_OWNER_2}.TOP_FIELD SET FIELD_TABLE=LTRIM(RTRIM(REPLACE(FIELD_TABLE,'${DP_OWNER}','${DP_OWNER_2}')));
COMMIT;
EOF