features:

SELECT NAME, DETECTED_USAGES, CURRENTLY_USED, FIRST_USAGE_DATE, LAST_USAGE_DATE FROM DBA_FEATURE_USAGE_STATISTICS 
ORDER BY LAST_USAGE_DATE DESC;

options:
SELECT PARAMETER, VALUE FROM V$OPTION ORDER BY 1;
