COL DB_NAME FORMAT A10
COL HOSTNAME FORMAT A15
COL ARCHIVE_LOCAL FORMAT 9999999999
COL REDO_ENVIADO FORMAT 9999999999
COL TEMPO_DE_APLICACAO FORMAT A12
SELECT DB_NAME, HOSTNAME, ARCHIVE_LOCAL, REDO_ENVIADO,TEMPO_DE_APLICACAO,ARCHIVE_LOCAL-REDO_ENVIADO REDOLOG_GAP
FROM
(SELECT NAME DB_NAME FROM V$DATABASE ),
(SELECT UPPER(SUBSTR(HOST_NAME,1,(DECODE(INSTR(HOST_NAME,'.'),0,LENGTH(HOST_NAME),(INSTR(HOST_NAME,'.')-1))))) HOSTNAME FROM V$INSTANCE ),
(SELECT MAX(SEQUENCE#) ARCHIVE_LOCAL FROM GV$ARCHIVED_LOG WHERE DEST_ID=1 AND ARCHIVED='YES' ),
(SELECT MAX(SEQUENCE#) REDO_ENVIADO FROM GV$ARCHIVED_LOG WHERE DEST_ID=2 AND APPLIED='YES'),
(SELECT TO_CHAR(MAX(COMPLETION_TIME),'DD-MON/HH24:MI') TEMPO_DE_APLICACAO FROM GV$ARCHIVED_LOG WHERE DEST_ID=2 AND APPLIED='YES');





###########


col DEST_NAME for a20
select INST_ID,DEST_ID,DEST_NAME,STATUS,TYPE,DATABASE_MODE,RECOVERY_MODE,SYNCHRONIZATION_STATUS,SYNCHRONIZED,GAP_STATUS 
from gV$ARCHIVE_DEST_STATUS where DEST_NAME in ('LOG_ARCHIVE_DEST_1','LOG_ARCHIVE_DEST_2');



 select
  thread#,
  dest_id,
  sequence#,
  first_time,
  next_time
  from v$archived_log
  where resetlogs_change# = (select resetlogs_change# from v$database)
  order by thread#, sequence#, dest_id;
