SELECT 
  --OWNER
  J.JOB_NAME
  ,TO_CHAR(J.LAST_START_DATE,'dd/mm/yyyy  hh24:mi:ss') AS "ULTIMA_EXECUCAO"
  ,J.SCHEDULE_NAME AS "SCHEDULE"
  ,S.REPEAT_INTERVAL AS "INT_SCHEDULER"
  ,J.REPEAT_INTERVAL AS "INT_JOB"
  --,TO_CHAR(D.LOG_DATE,'dd/mm/yyyy  hh24:mi:ss') AS "TERMINO_EXECUCAO"
  ,SUBSTR(J.LAST_RUN_DURATION,9) AS "DURACAO"
  ,J.JOB_ACTION AS "COMANDO"
  ,J.COMMENTS AS "COMENTARIOS"
  FROM 
    DBA_SCHEDULER_JOBS J LEFT JOIN DBA_SCHEDULER_SCHEDULES S
  ON 
  J.SCHEDULE_NAME = S.SCHEDULE_NAME
   WHERE J.OWNER in ('DBAASS','POS_EAD')
    ORDER BY 1