
create user U_SOUDIGITAL identified by digora#2017#05#18;

create role R_SOUDIGITAL;

GRANT SELECT ON ALUNO_SEMESTRE TO R_SOUDIGITAL;
GRANT SELECT ON VM_ALUNO_SEMESTRE_ULT TO R_SOUDIGITAL;
GRANT SELECT ON NATUREZA TO R_SOUDIGITAL;
GRANT SELECT ON TURMA_SEMESTRE TO R_SOUDIGITAL;
GRANT SELECT ON TITULO TO R_SOUDIGITAL;
GRANT SELECT ON NFSE_ORIGEM TO R_SOUDIGITAL;
GRANT SELECT ON CURSO TO R_SOUDIGITAL;
GRANT SELECT ON EXAME_SELECAO TO R_SOUDIGITAL;
GRANT SELECT ON POS_EAD.POS_FATURAMENTO TO R_SOUDIGITAL;
GRANT SELECT ON CONVENIO_ALSE_MENSALIDADE TO R_SOUDIGITAL;
GRANT SELECT ON CONVENIO_SESE TO R_SOUDIGITAL;
GRANT SELECT ON CONVENIO_TIPO_SESE TO R_SOUDIGITAL;
GRANT SELECT ON CONVENIO_TIPO TO R_SOUDIGITAL;
GRANT SELECT ON PESSOA TO R_SOUDIGITAL;
GRANT SELECT ON VM_ESPECIALIZACAO TO R_SOUDIGITAL;
GRANT SELECT ON ALUNO TO R_SOUDIGITAL;
GRANT SELECT ON CIDADE TO R_SOUDIGITAL;
GRANT SELECT ON ESELECAO_CURSO TO R_SOUDIGITAL;
grant create session to R_SOUDIGITAL;
GRANT R_SOUDIGITAL TO U_SOUDIGITAL;
