SET LINESIZE 100
SET PAGESIZE 300
SET LONG 1
SELECT DECODE (GROUPING(TABLESPACE_NAME),1, 'XTOTAL DATAFILES',TABLESPACE_NAME) "TABLESPACE", COUNT(*) "QTDE", SUM(MAXBYTES/1048576) "TOTAL_MB", SUM(BYTES/1048576) "USADO_MB",
--TO_CHAR(((SUM(BYTES/1048576))*100/(SUM(MAXBYTES/1048576))),'999.99') ||'%' AS "% USADO"
FROM DBA_DATA_FILES GROUP BY ROLLUP(TABLESPACE_NAME)
UNION ALL
SELECT DECODE (GROUPING(TABLESPACE_NAME),1, 'XTOTAL TEMPFILES',TABLESPACE_NAME) "TABLESPACE", COUNT(*) "QTDE", SUM(MAXBYTES/1048576) "TOTAL_MB", SUM(BYTES/1048576) "USADO_MB",
--TO_CHAR(((SUM(BYTES/1048576))*100/(SUM(MAXBYTES/1048576))),'999.99') ||'%' AS "% USADO"
FROM DBA_TEMP_FILES GROUP BY ROLLUP(TABLESPACE_NAME)
ORDER BY 1 ASC;

===========================================

SET LINES 300
SET PAGESIZE 200
SELECT D.TABLESPACE_NAME "NAME", D.STATUS "STATUS", A.BYTES/ 1048576 "TOTAL(M)", F.BYTES / 1048576 "LIVRE(M)", ((A.BYTES - DECODE(F.BYTES, NULL, 0, F.BYTES)) / 1048576) "ALOCADO(M)", D.BLOCK_SIZE FROM SYS.DBA_TABLESPACES D, SYS.SM$TS_AVAIL A, SYS.SM$TS_FREE F WHERE D.TABLESPACE_NAME = A.TABLESPACE_NAME AND F.TABLESPACE_NAME (+) = D.TABLESPACE_NAME ORDER BY 3 DESC;

===========================================

SELECT 
	DF.TABLESPACE_NAME "TABLESPACE", (DF.ACTUALSPACE - FS.FREESPACE) "USED MB", FS.FREESPACE "F_ACT MB", DF.ACTUALSPACE "ACT MB", ROUND(100 * (FS.FREESPACE / DF.ACTUALSPACE)) "F_ACT %", (DF.ACTUALSPACE - DD.TOTALSPACE) "F_TOT MB", DD.TOTALSPACE "TOT MB"
   --ROUND(100 * ((DD.TOTALSPACE - DF.ACTUALSPACE) / DD.TOTALSPACE)) "F_TOT %"
FROM
   (SELECT TABLESPACE_NAME, ROUND(SUM(BYTES) / 1048576) ACTUALSPACE FROM DBA_DATA_FILES GROUP BY TABLESPACE_NAME) DF,
   (SELECT TABLESPACE_NAME, ROUND(SUM(BYTES) / 1048576) FREESPACE FROM DBA_FREE_SPACE GROUP BY TABLESPACE_NAME) FS,
   (SELECT TABLESPACE_NAME, ROUND(SUM(MAXBYTES) / 1048576) TOTALSPACE FROM DBA_DATA_FILES GROUP BY TABLESPACE_NAME) DD
WHERE
   DF.TABLESPACE_NAME = FS.TABLESPACE_NAME(+) AND DF.TABLESPACE_NAME = DD.TABLESPACE_NAME(+) ORDER BY 1;
   
===========================================

-- TAMANHO TOTAL DO BD
SET PAGESIZE 100
SELECT D.TABLESPACE_NAME "NAME", SUM(((A.BYTES - DECODE(F.BYTES, NULL, 0, F.BYTES)) / 1048576)) "TOTAL_UTILIZADO (MB)"
FROM SYS.DBA_TABLESPACES D, SYS.SM$TS_AVAIL A,  SYS.SM$TS_FREE F
WHERE D.TABLESPACE_NAME = A.TABLESPACE_NAME AND F.TABLESPACE_NAME (+) = D.TABLESPACE_NAME
GROUP BY ROLLUP(D.TABLESPACE_NAME);
   
===========================================

-- TEMPORARY TABLESPACE SORT USAGE.
SET PAUSE ON
SET PAUSE 'PRESS RETURN TO CONTINUE'
SET PAGESIZE 60
SET LINESIZE 300
SELECT A.TABLESPACE_NAME TABLESPACE, D.MB_TOTAL, SUM (A.USED_BLOCKS * D.BLOCK_SIZE) / 1024 / 1024 MB_USED, D.MB_TOTAL - SUM (A.USED_BLOCKS * D.BLOCK_SIZE) / 1024 / 1024 MB_FREE FROM V$SORT_SEGMENT A,
(
SELECT B.NAME, C.BLOCK_SIZE, SUM (C.BYTES) / 1024 / 1024 MB_TOTAL FROM V$TABLESPACE B, V$TEMPFILE C WHERE B.TS#= C.TS# GROUP BY B.NAME,  C.BLOCK_SIZE
) D
WHERE A.TABLESPACE_NAME = D.NAME GROUP BY A.TABLESPACE_NAME, D.MB_TOTAL;