set verify off
COLUMN I           	FORMAT 9
COLUMN PARAMETER_NAME  	FORMAT a30 WORD_WRAPPED
COLUMN BEGIN_INTERVAL_TIME  	FORMAT a20 WORD_WRAPPED
COLUMN VALUE    	FORMAT a50 WORD_WRAPPED
set lines 1000 pages 999
 
select p.INSTANCE_NUMBER I,
to_char(BEGIN_INTERVAL_TIME,'MM/DD/YYYY HH24:MI:SS') BEGIN_INTERVAL_TIME,
p.PARAMETER_NAME,
VALUE
from DBA_HIST_PARAMETER p,DBA_HIST_SNAPSHOT s
where s.SNAP_ID=p.SNAP_ID
and s.dbid=p.dbid
and s.INSTANCE_NUMBER=p.INSTANCE_NUMBER
and s.BEGIN_INTERVAL_TIME > sysdate-&2/24
and p.PARAMETER_NAME like '%&1%'
order by 2,1;

undefine 1
