set verify off
COLUMN ID           	FORMAT 9
COLUMN NAME         	FORMAT a30 WORD_WRAPPED
COLUMN DISPLAY_VALUE    FORMAT a50 WORD_WRAPPED
COLUMN ISDEFAULT 	FORMAT a9
COLUMN ISSYS_MODIFIABLE FORMAT a9
COLUMN ISINSTANCE_MODIFIABLE FORMAT a5
set lines 1000 pages 999
 
SELECT
INST_ID ID,
NAME,
DISPLAY_VALUE,
ISDEFAULT,
ISSYS_MODIFIABLE
FROM
   gv$parameter 
WHERE
   name LIKE '%&1%' 
ORDER BY NAME
;

undefine 1
