prompt Checking blocking locks more than 3 mins...
set lines 300 pages 999
COL "HIERARCHY"          FORMAT A9      HEAD 'HIERARCHY' WORD_WRAPPED
COL HELD_MIN 		 FORMAT A10
COL WAIT_MIN		 FORMAT A10
COL "STATUS"             FORMAT A8      HEAD 'STATUS'
COL "LAST_CALL_ET"       FORMAT 999999  HEAD 'LAST|CALL'
COL "INST_ID:SID:SERIAL" FORMAT A19     HEAD 'INST_ID:SID:SERIAL#' WORD_WRAPPED
COL "USERNAME"           FORMAT A25     HEAD 'USERNAME' WORD_WRAPPED
COL "SESSION LMODE"      FORMAT A7      HEAD 'SESS|LMODE' WORD_WRAPPED
COL "OBJ LMODE"          FORMAT A7     HEAD 'OBJ|LMODE' WORD_WRAPPED
COL "TYPE"               FORMAT A4     HEAD 'LOCK|TYPE' WORD_WRAPPED
COL "OBJ NAME"           FORMAT A35    HEAD 'OBJECT LOCKED/REQUESTED' WORD_WRAPPED
COL "ID1"                FORMAT 9999999999 HEAD 'ID1'
COL "ID2"                FORMAT 9999999999 HEAD 'ID2'
COL "SQL_ID"             FORMAT A14    HEAD 'SQL ID'
COL "PROCESS"            FORMAT A12    HEAD 'PROCESS ID'
COL "MACHINE"            FORMAT A30    HEAD 'MACHINE' WORD_WRAPPED
COL "TXNADDR"            NOPRINT

SELECT /*+ RULE */ DISTINCT
       CASE VL.REQUEST
           WHEN 0 THEN 'HOLDER'
           ELSE ' ->WAITER'
       END as "HIERARCHY",
      CASE VL.REQUEST
            WHEN 0 THEN TO_CHAR(VL.CTIME/60, 999999.99)
            ELSE NULL
         END AS HELD_MIN,
       CASE VL.REQUEST
            WHEN 0 THEN NULL
            ELSE TO_CHAR(VL.CTIME/60, 999999.99)
        END AS WAIT_MIN,
       VS.INST_ID || ':' || VS.SID || ':' || VS.SERIAL# as "INST_ID:SID:SERIAL",
       VS.MACHINE, VS.STATUS,VS.SQL_ID,VS.LAST_CALL_ET ,
       CASE VL.LMODE
            WHEN 0 THEN 'none'
            WHEN 1 THEN '(NULL)'
            WHEN 2 THEN '(SS)'
            WHEN 3 THEN '(SX)'
            WHEN 4 THEN '(S)'
            WHEN 5 THEN '(SSX)'
            WHEN 6 THEN '(X)'
            ELSE 'Unknown'
        END AS "SESSION LMODE",
       CASE VLO.LOCKED_MODE
            WHEN 0 THEN 'none'
            WHEN 1 THEN '(NULL)'
            WHEN 2 THEN '(SS)'
            WHEN 3 THEN '(SX)'
            WHEN 4 THEN '(S)'
            WHEN 5 THEN '(SSX)'
            WHEN 6 THEN '(X)'
            ELSE 'Unknown'
        END AS "OBJ LMODE",
        VL.TYPE AS TYPE,
/*       CASE WHEN VL.REQUEST = 0 THEN DBO.OWNER||'.'||DBO.OBJECT_NAME
            WHEN VL.REQUEST > 0 then DBO_REQ.OWNER||'.'||DBO_REQ.OBJECT_NAME
            ELSE NULL
        END AS "OBJ NAME",
*/
       VL.ID1,
--       VL.ID2,
       VS.USERNAME as USERNAME
FROM GV$LOCK VL
     INNER JOIN GV$SESSION VS
             ON VS.SID = VL.SID and VS.INST_ID=VL.INST_ID
     LEFT OUTER JOIN GV$LOCKED_OBJECT VLO
             ON VL.SID = VLO.SESSION_ID and VL.INST_ID = VLO.INST_ID
     LEFT OUTER JOIN DBA_OBJECTS DBO
             ON DBO.OBJECT_ID = VLO.OBJECT_ID
     LEFT OUTER JOIN DBA_OBJECTS DBO_REQ
             ON DBO_REQ.OBJECT_ID = VS.ROW_WAIT_OBJ#
WHERE (VL.ID1, VL.ID2, VL.TYPE) IN
      (SELECT VLI.ID1, VLI.ID2, VLI.TYPE
        FROM GV$LOCK VLI, GV$SESSION VSI
       WHERE VSI.LOCKWAIT IS NOT NULL
         AND VSI.SID = VLI.SID
         AND VLI.INST_ID = VSI.INST_ID
         AND VLI.REQUEST>0
         AND VL.TYPE != 'RO'
         AND VLI.CTIME >= 180)
ORDER BY VL.ID1, HIERARCHY DESC,WAIT_MIN DESC;

CLEAR COLUMNS;
